// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.3
// source: iam/grant/v1/grant.proto

package grantv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// GrantServiceKernelModule returns the generated Kernel service module for iam.grant.v1.GrantService.
func GrantServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "grant-service",
		GatewayManifest:     GrantServiceGatewayManifest(),
		RequestInfoResolver: GrantServiceKernelRequestInfoResolver,
		AccessResolver:      GrantServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(GrantServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.grant.v1.GrantService must implement GrantServiceServer, got %T", impl)
			}
			RegisterGrantServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(GrantServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.grant.v1.GrantService must implement GrantServiceHTTPServer, got %T", impl)
			}
			RegisterGrantServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(GrantServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.grant.v1.GrantService must implement GrantServiceClient, got %T", client)
			}
			return RegisterGrantServiceGatewayInvokers(r, typed)
		},
	}
}

var GrantServiceKernelAuthzRules = authz.Rules{
	"/iam.grant.v1.GrantService/RegisterRoleTemplate": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "RegisterRoleTemplate",
		FullMethod: "/iam.grant.v1.GrantService/RegisterRoleTemplate",
		Action:     "manage",
		Resource:   "iam:role_template",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.role_template.register",
		AuditRisk:  "high",
	},
	"/iam.grant.v1.GrantService/ListRoleTemplates": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "ListRoleTemplates",
		FullMethod: "/iam.grant.v1.GrantService/ListRoleTemplates",
		Action:     "list",
		Resource:   "iam:role_template",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.role_template.list",
		AuditRisk:  "medium",
	},
	"/iam.grant.v1.GrantService/GrantAccess": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "GrantAccess",
		FullMethod: "/iam.grant.v1.GrantService/GrantAccess",
		Action:     "grant",
		Resource:   "iam:grant",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.grant.create",
		AuditRisk:  "high",
	},
	"/iam.grant.v1.GrantService/RevokeAccess": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "RevokeAccess",
		FullMethod: "/iam.grant.v1.GrantService/RevokeAccess",
		Action:     "revoke",
		Resource:   "iam:grant:{grant_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.grant.revoke",
		AuditRisk:  "high",
	},
	"/iam.grant.v1.GrantService/ListGrants": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "ListGrants",
		FullMethod: "/iam.grant.v1.GrantService/ListGrants",
		Action:     "list",
		Resource:   "iam:grant",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.grant.list",
		AuditRisk:  "medium",
	},
	"/iam.grant.v1.GrantService/ExplainAccess": {
		Service:    "iam.grant.v1.GrantService",
		Method:     "ExplainAccess",
		FullMethod: "/iam.grant.v1.GrantService/ExplainAccess",
		Action:     "explain",
		Resource:   "iam:grant",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.access.explain",
		AuditRisk:  "medium",
	},
}

// GrantServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func GrantServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _GrantServiceKernelNormalizeOperation(operation) {
	case "/iam.grant.v1.GrantService/RegisterRoleTemplate":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "RegisterRoleTemplate",
			Operation:     "/iam.grant.v1.GrantService/RegisterRoleTemplate",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "iam:role_template",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.role_template.register"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.grant.v1.GrantService/ListRoleTemplates":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "ListRoleTemplates",
			Operation:     "/iam.grant.v1.GrantService/ListRoleTemplates",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "list",
			Resource:      "iam:role_template",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.role_template.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.grant.v1.GrantService/GrantAccess":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "GrantAccess",
			Operation:     "/iam.grant.v1.GrantService/GrantAccess",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "grant",
			Resource:      "iam:grant",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.grant.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.grant.v1.GrantService/RevokeAccess":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "RevokeAccess",
			Operation:     "/iam.grant.v1.GrantService/RevokeAccess",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "revoke",
			Resource:      "iam:grant:{grant_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.grant.revoke"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.grant.v1.GrantService/ListGrants":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "ListGrants",
			Operation:     "/iam.grant.v1.GrantService/ListGrants",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "list",
			Resource:      "iam:grant",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.grant.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.grant.v1.GrantService/ExplainAccess":
		info := requestx.Info{
			Service:       "iam.grant.v1.GrantService",
			Method:        "ExplainAccess",
			Operation:     "/iam.grant.v1.GrantService/ExplainAccess",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "explain",
			Resource:      "iam:grant",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.access.explain"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// GrantServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func GrantServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := GrantServiceKernelAuthzRules[_GrantServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _GrantServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "RegisterRoleTemplate", "iam.grant.v1.GrantService/RegisterRoleTemplate":
		return "/iam.grant.v1.GrantService/RegisterRoleTemplate"
	case "ListRoleTemplates", "iam.grant.v1.GrantService/ListRoleTemplates":
		return "/iam.grant.v1.GrantService/ListRoleTemplates"
	case "GrantAccess", "iam.grant.v1.GrantService/GrantAccess":
		return "/iam.grant.v1.GrantService/GrantAccess"
	case "RevokeAccess", "iam.grant.v1.GrantService/RevokeAccess":
		return "/iam.grant.v1.GrantService/RevokeAccess"
	case "ListGrants", "iam.grant.v1.GrantService/ListGrants":
		return "/iam.grant.v1.GrantService/ListGrants"
	case "ExplainAccess", "iam.grant.v1.GrantService/ExplainAccess":
		return "/iam.grant.v1.GrantService/ExplainAccess"
	default:
		return operation
	}
}
