// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.2.1
// - protoc             (unknown)
// source: iam/grant/v1/grant.proto

package grantv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationGrantServiceExplainAccess = "/iam.grant.v1.GrantService/ExplainAccess"
const OperationGrantServiceGrantAccess = "/iam.grant.v1.GrantService/GrantAccess"
const OperationGrantServiceListGrants = "/iam.grant.v1.GrantService/ListGrants"
const OperationGrantServiceListRoleTemplates = "/iam.grant.v1.GrantService/ListRoleTemplates"
const OperationGrantServiceRegisterRoleTemplate = "/iam.grant.v1.GrantService/RegisterRoleTemplate"
const OperationGrantServiceRevokeAccess = "/iam.grant.v1.GrantService/RevokeAccess"

type GrantServiceHTTPServer interface {
	ExplainAccess(context.Context, *ExplainAccessRequest) (*ExplainAccessReply, error)
	GrantAccess(context.Context, *GrantAccessRequest) (*Grant, error)
	ListGrants(context.Context, *ListGrantsRequest) (*ListGrantsReply, error)
	ListRoleTemplates(context.Context, *ListRoleTemplatesRequest) (*ListRoleTemplatesReply, error)
	RegisterRoleTemplate(context.Context, *RegisterRoleTemplateRequest) (*RoleTemplate, error)
	RevokeAccess(context.Context, *RevokeAccessRequest) (*RevokeAccessReply, error)
}

func RegisterGrantServiceHTTPServer(s *http.Server, srv GrantServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/iam/control-plane/grants", _GrantService_ListGrants0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/role-templates", _GrantService_ListRoleTemplates0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/access:explain", _GrantService_ExplainAccess0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/grants", _GrantService_GrantAccess0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/role-templates", _GrantService_RegisterRoleTemplate0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/grants/{grant_id}/revoke", _GrantService_RevokeAccess0_HTTP_Handler(srv))
}

func _GrantService_ListGrants0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGrantsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceListGrants)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGrants(ctx, req.(*ListGrantsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGrantsReply)
		return ctx.Result(200, reply)
	}
}

func _GrantService_ListRoleTemplates0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoleTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceListRoleTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoleTemplates(ctx, req.(*ListRoleTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoleTemplatesReply)
		return ctx.Result(200, reply)
	}
}

func _GrantService_ExplainAccess0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExplainAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceExplainAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExplainAccess(ctx, req.(*ExplainAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExplainAccessReply)
		return ctx.Result(200, reply)
	}
}

func _GrantService_GrantAccess0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GrantAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceGrantAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GrantAccess(ctx, req.(*GrantAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Grant)
		return ctx.Result(200, reply)
	}
}

func _GrantService_RegisterRoleTemplate0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterRoleTemplateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceRegisterRoleTemplate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterRoleTemplate(ctx, req.(*RegisterRoleTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleTemplate)
		return ctx.Result(200, reply)
	}
}

func _GrantService_RevokeAccess0_HTTP_Handler(srv GrantServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RevokeAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGrantServiceRevokeAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeAccess(ctx, req.(*RevokeAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RevokeAccessReply)
		return ctx.Result(200, reply)
	}
}

type GrantServiceHTTPClient interface {
	ExplainAccess(ctx context.Context, req *ExplainAccessRequest, opts ...http.CallOption) (rsp *ExplainAccessReply, err error)
	GrantAccess(ctx context.Context, req *GrantAccessRequest, opts ...http.CallOption) (rsp *Grant, err error)
	ListGrants(ctx context.Context, req *ListGrantsRequest, opts ...http.CallOption) (rsp *ListGrantsReply, err error)
	ListRoleTemplates(ctx context.Context, req *ListRoleTemplatesRequest, opts ...http.CallOption) (rsp *ListRoleTemplatesReply, err error)
	RegisterRoleTemplate(ctx context.Context, req *RegisterRoleTemplateRequest, opts ...http.CallOption) (rsp *RoleTemplate, err error)
	RevokeAccess(ctx context.Context, req *RevokeAccessRequest, opts ...http.CallOption) (rsp *RevokeAccessReply, err error)
}

type GrantServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGrantServiceHTTPClient(client *http.Client) GrantServiceHTTPClient {
	return &GrantServiceHTTPClientImpl{client}
}

func (c *GrantServiceHTTPClientImpl) ExplainAccess(ctx context.Context, in *ExplainAccessRequest, opts ...http.CallOption) (*ExplainAccessReply, error) {
	var out ExplainAccessReply
	pattern := "/v1/iam/control-plane/access:explain"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGrantServiceExplainAccess),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GrantServiceHTTPClientImpl) GrantAccess(ctx context.Context, in *GrantAccessRequest, opts ...http.CallOption) (*Grant, error) {
	var out Grant
	pattern := "/v1/iam/control-plane/grants"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGrantServiceGrantAccess),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GrantServiceHTTPClientImpl) ListGrants(ctx context.Context, in *ListGrantsRequest, opts ...http.CallOption) (*ListGrantsReply, error) {
	var out ListGrantsReply
	pattern := "/v1/iam/control-plane/grants"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGrantServiceListGrants),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GrantServiceHTTPClientImpl) ListRoleTemplates(ctx context.Context, in *ListRoleTemplatesRequest, opts ...http.CallOption) (*ListRoleTemplatesReply, error) {
	var out ListRoleTemplatesReply
	pattern := "/v1/iam/control-plane/role-templates"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGrantServiceListRoleTemplates),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GrantServiceHTTPClientImpl) RegisterRoleTemplate(ctx context.Context, in *RegisterRoleTemplateRequest, opts ...http.CallOption) (*RoleTemplate, error) {
	var out RoleTemplate
	pattern := "/v1/iam/control-plane/role-templates"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGrantServiceRegisterRoleTemplate),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GrantServiceHTTPClientImpl) RevokeAccess(ctx context.Context, in *RevokeAccessRequest, opts ...http.CallOption) (*RevokeAccessReply, error) {
	var out RevokeAccessReply
	pattern := "/v1/iam/control-plane/grants/{grant_id}/revoke"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGrantServiceRevokeAccess),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
