// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iam/grant/v1/grant.proto

package grantv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/aisphereio/aisphere-iam/api/iam/resource/v1"
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleTemplate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceType     string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	RoleKey          string                 `protobuf:"bytes,3,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	DisplayName      string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description      string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Relation         string                 `protobuf:"bytes,6,opt,name=relation,proto3" json:"relation,omitempty"`
	BuiltIn          bool                   `protobuf:"varint,7,opt,name=built_in,json=builtIn,proto3" json:"built_in,omitempty"`
	Enabled          bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SortOrder        int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Permissions      []string               `protobuf:"bytes,14,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ActiveGrantCount int64                  `protobuf:"varint,15,opt,name=active_grant_count,json=activeGrantCount,proto3" json:"active_grant_count,omitempty"`
	Version          int64                  `protobuf:"varint,16,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoleTemplate) Reset() {
	*x = RoleTemplate{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTemplate) ProtoMessage() {}

func (x *RoleTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTemplate.ProtoReflect.Descriptor instead.
func (*RoleTemplate) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{0}
}

func (x *RoleTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleTemplate) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *RoleTemplate) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *RoleTemplate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RoleTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleTemplate) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RoleTemplate) GetBuiltIn() bool {
	if x != nil {
		return x.BuiltIn
	}
	return false
}

func (x *RoleTemplate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RoleTemplate) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *RoleTemplate) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoleTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RoleTemplate) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleTemplate) GetActiveGrantCount() int64 {
	if x != nil {
		return x.ActiveGrantCount
	}
	return 0
}

func (x *RoleTemplate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Grant struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource         *v1.ResourceRef        `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	RoleKey          string                 `protobuf:"bytes,3,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Relation         string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject          *v1.SubjectRef         `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Source           string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Reason           string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedBy        *v1.SubjectRef         `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,12,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{1}
}

func (x *Grant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grant) GetResource() *v1.ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Grant) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *Grant) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Grant) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Grant) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Grant) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Grant) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Grant) GetCreatedBy() *v1.SubjectRef {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Grant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Grant) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *Grant) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

func (x *Grant) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterRoleTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleTemplate  *RoleTemplate          `protobuf:"bytes,1,opt,name=role_template,json=roleTemplate,proto3" json:"role_template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRoleTemplateRequest) Reset() {
	*x = RegisterRoleTemplateRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRoleTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRoleTemplateRequest) ProtoMessage() {}

func (x *RegisterRoleTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRoleTemplateRequest.ProtoReflect.Descriptor instead.
func (*RegisterRoleTemplateRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRoleTemplateRequest) GetRoleTemplate() *RoleTemplate {
	if x != nil {
		return x.RoleTemplate
	}
	return nil
}

type UpdateRoleTemplateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permissions     []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRoleTemplateRequest) Reset() {
	*x = UpdateRoleTemplateRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleTemplateRequest) ProtoMessage() {}

func (x *UpdateRoleTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleTemplateRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRoleTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleTemplateRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateRoleTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleTemplateRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateRoleTemplateRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type DisableRoleTemplateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpectedVersion     int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	ConfirmActiveGrants bool                   `protobuf:"varint,3,opt,name=confirm_active_grants,json=confirmActiveGrants,proto3" json:"confirm_active_grants,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DisableRoleTemplateRequest) Reset() {
	*x = DisableRoleTemplateRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableRoleTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableRoleTemplateRequest) ProtoMessage() {}

func (x *DisableRoleTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableRoleTemplateRequest.ProtoReflect.Descriptor instead.
func (*DisableRoleTemplateRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{4}
}

func (x *DisableRoleTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DisableRoleTemplateRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *DisableRoleTemplateRequest) GetConfirmActiveGrants() bool {
	if x != nil {
		return x.ConfirmActiveGrants
	}
	return false
}

type PreviewRoleTemplateImpactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRoleTemplateImpactRequest) Reset() {
	*x = PreviewRoleTemplateImpactRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRoleTemplateImpactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRoleTemplateImpactRequest) ProtoMessage() {}

func (x *PreviewRoleTemplateImpactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRoleTemplateImpactRequest.ProtoReflect.Descriptor instead.
func (*PreviewRoleTemplateImpactRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{5}
}

func (x *PreviewRoleTemplateImpactRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PreviewRoleTemplateImpactRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PreviewRoleTemplateImpactReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActiveGrantCount   int64                  `protobuf:"varint,1,opt,name=active_grant_count,json=activeGrantCount,proto3" json:"active_grant_count,omitempty"`
	AddedPermissions   []string               `protobuf:"bytes,2,rep,name=added_permissions,json=addedPermissions,proto3" json:"added_permissions,omitempty"`
	RemovedPermissions []string               `protobuf:"bytes,3,rep,name=removed_permissions,json=removedPermissions,proto3" json:"removed_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PreviewRoleTemplateImpactReply) Reset() {
	*x = PreviewRoleTemplateImpactReply{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRoleTemplateImpactReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRoleTemplateImpactReply) ProtoMessage() {}

func (x *PreviewRoleTemplateImpactReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRoleTemplateImpactReply.ProtoReflect.Descriptor instead.
func (*PreviewRoleTemplateImpactReply) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{6}
}

func (x *PreviewRoleTemplateImpactReply) GetActiveGrantCount() int64 {
	if x != nil {
		return x.ActiveGrantCount
	}
	return 0
}

func (x *PreviewRoleTemplateImpactReply) GetAddedPermissions() []string {
	if x != nil {
		return x.AddedPermissions
	}
	return nil
}

func (x *PreviewRoleTemplateImpactReply) GetRemovedPermissions() []string {
	if x != nil {
		return x.RemovedPermissions
	}
	return nil
}

type ListRoleTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	RoleKey       string                 `protobuf:"bytes,2,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Enabled       *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleTemplatesRequest) Reset() {
	*x = ListRoleTemplatesRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleTemplatesRequest) ProtoMessage() {}

func (x *ListRoleTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListRoleTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{7}
}

func (x *ListRoleTemplatesRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ListRoleTemplatesRequest) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *ListRoleTemplatesRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

type ListRoleTemplatesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleTemplates []*RoleTemplate        `protobuf:"bytes,1,rep,name=role_templates,json=roleTemplates,proto3" json:"role_templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoleTemplatesReply) Reset() {
	*x = ListRoleTemplatesReply{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoleTemplatesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoleTemplatesReply) ProtoMessage() {}

func (x *ListRoleTemplatesReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoleTemplatesReply.ProtoReflect.Descriptor instead.
func (*ListRoleTemplatesReply) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoleTemplatesReply) GetRoleTemplates() []*RoleTemplate {
	if x != nil {
		return x.RoleTemplates
	}
	return nil
}

type GrantAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *v1.ResourceRef        `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	RoleKey       string                 `protobuf:"bytes,2,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantAccessRequest) Reset() {
	*x = GrantAccessRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantAccessRequest) ProtoMessage() {}

func (x *GrantAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantAccessRequest.ProtoReflect.Descriptor instead.
func (*GrantAccessRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{9}
}

func (x *GrantAccessRequest) GetResource() *v1.ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *GrantAccessRequest) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *GrantAccessRequest) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *GrantAccessRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GrantAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GrantAccessRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GrantAccessRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RevokeAccessRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	GrantId                 string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Reason                  string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DeleteGraphRelationship bool                   `protobuf:"varint,3,opt,name=delete_graph_relationship,json=deleteGraphRelationship,proto3" json:"delete_graph_relationship,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RevokeAccessRequest) Reset() {
	*x = RevokeAccessRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessRequest) ProtoMessage() {}

func (x *RevokeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessRequest.ProtoReflect.Descriptor instead.
func (*RevokeAccessRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAccessRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RevokeAccessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RevokeAccessRequest) GetDeleteGraphRelationship() bool {
	if x != nil {
		return x.DeleteGraphRelationship
	}
	return false
}

type RevokeAccessReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GrantId          string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Revoked          bool                   `protobuf:"varint,2,opt,name=revoked,proto3" json:"revoked,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeAccessReply) Reset() {
	*x = RevokeAccessReply{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAccessReply) ProtoMessage() {}

func (x *RevokeAccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAccessReply.ProtoReflect.Descriptor instead.
func (*RevokeAccessReply) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeAccessReply) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RevokeAccessReply) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

func (x *RevokeAccessReply) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

type ListGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *v1.ResourceRef        `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	RoleKey       string                 `protobuf:"bytes,4,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Active        *bool                  `protobuf:"varint,6,opt,name=active,proto3,oneof" json:"active,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,8,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGrantsRequest) Reset() {
	*x = ListGrantsRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGrantsRequest) ProtoMessage() {}

func (x *ListGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGrantsRequest.ProtoReflect.Descriptor instead.
func (*ListGrantsRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{12}
}

func (x *ListGrantsRequest) GetResource() *v1.ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ListGrantsRequest) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ListGrantsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListGrantsRequest) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

func (x *ListGrantsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListGrantsRequest) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ListGrantsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGrantsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListGrantsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []*Grant               `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGrantsReply) Reset() {
	*x = ListGrantsReply{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGrantsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGrantsReply) ProtoMessage() {}

func (x *ListGrantsReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGrantsReply.ProtoReflect.Descriptor instead.
func (*ListGrantsReply) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{13}
}

func (x *ListGrantsReply) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

func (x *ListGrantsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListGrantsReply) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type ExplainAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *v1.ResourceRef        `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainAccessRequest) Reset() {
	*x = ExplainAccessRequest{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainAccessRequest) ProtoMessage() {}

func (x *ExplainAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainAccessRequest.ProtoReflect.Descriptor instead.
func (*ExplainAccessRequest) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{14}
}

func (x *ExplainAccessRequest) GetResource() *v1.ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExplainAccessRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *ExplainAccessRequest) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

type ExplainStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Resource      *v1.ResourceRef        `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Subject       *v1.SubjectRef         `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainStep) Reset() {
	*x = ExplainStep{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainStep) ProtoMessage() {}

func (x *ExplainStep) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainStep.ProtoReflect.Descriptor instead.
func (*ExplainStep) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{15}
}

func (x *ExplainStep) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExplainStep) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ExplainStep) GetResource() *v1.ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExplainStep) GetSubject() *v1.SubjectRef {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *ExplainStep) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExplainAccessReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Allowed          bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Effect           string                 `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	Reason           string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Steps            []*ExplainStep         `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	ConsistencyToken string                 `protobuf:"bytes,5,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExplainAccessReply) Reset() {
	*x = ExplainAccessReply{}
	mi := &file_iam_grant_v1_grant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainAccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainAccessReply) ProtoMessage() {}

func (x *ExplainAccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_grant_v1_grant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainAccessReply.ProtoReflect.Descriptor instead.
func (*ExplainAccessReply) Descriptor() ([]byte, []int) {
	return file_iam_grant_v1_grant_proto_rawDescGZIP(), []int{16}
}

func (x *ExplainAccessReply) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ExplainAccessReply) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *ExplainAccessReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ExplainAccessReply) GetSteps() []*ExplainStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ExplainAccessReply) GetConsistencyToken() string {
	if x != nil {
		return x.ConsistencyToken
	}
	return ""
}

var File_iam_grant_v1_grant_proto protoreflect.FileDescriptor

const file_iam_grant_v1_grant_proto_rawDesc = "" +
	"\n" +
	"\x18iam/grant/v1/grant.proto\x12\fiam.grant.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eiam/resource/v1/resource.proto\"\xa8\x04\n" +
	"\fRoleTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12\x19\n" +
	"\brole_key\x18\x03 \x01(\tR\aroleKey\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\brelation\x18\x06 \x01(\tR\brelation\x12\x19\n" +
	"\bbuilt_in\x18\a \x01(\bR\abuiltIn\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12 \n" +
	"\vpermissions\x18\x0e \x03(\tR\vpermissions\x12,\n" +
	"\x12active_grant_count\x18\x0f \x01(\x03R\x10activeGrantCount\x12\x18\n" +
	"\aversion\x18\x10 \x01(\x03R\aversion\"\xbe\x04\n" +
	"\x05Grant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\bresource\x18\x02 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\bresource\x12\x19\n" +
	"\brole_key\x18\x03 \x01(\tR\aroleKey\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x125\n" +
	"\asubject\x18\x05 \x01(\v2\x1b.iam.resource.v1.SubjectRefR\asubject\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\n" +
	"created_by\x18\t \x01(\v2\x1b.iam.resource.v1.SubjectRefR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x12+\n" +
	"\x11consistency_token\x18\f \x01(\tR\x10consistencyToken\x123\n" +
	"\bmetadata\x18\r \x01(\v2\x17.google.protobuf.StructR\bmetadata\"c\n" +
	"\x1bRegisterRoleTemplateRequest\x12D\n" +
	"\rrole_template\x18\x01 \x01(\v2\x1a.iam.grant.v1.RoleTemplateB\x03\xe0A\x02R\froleTemplate\"\xd2\x01\n" +
	"\x19UpdateRoleTemplateRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x122\n" +
	"\x10expected_version\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\x0fexpectedVersion\"\xa0\x01\n" +
	"\x1aDisableRoleTemplateRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x122\n" +
	"\x10expected_version\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\x0fexpectedVersion\x122\n" +
	"\x15confirm_active_grants\x18\x03 \x01(\bR\x13confirmActiveGrants\"`\n" +
	" PreviewRoleTemplateImpactRequest\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\xac\x01\n" +
	"\x1ePreviewRoleTemplateImpactReply\x12,\n" +
	"\x12active_grant_count\x18\x01 \x01(\x03R\x10activeGrantCount\x12+\n" +
	"\x11added_permissions\x18\x02 \x03(\tR\x10addedPermissions\x12/\n" +
	"\x13removed_permissions\x18\x03 \x03(\tR\x12removedPermissions\"\x85\x01\n" +
	"\x18ListRoleTemplatesRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x19\n" +
	"\brole_key\x18\x02 \x01(\tR\aroleKey\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x00R\aenabled\x88\x01\x01B\n" +
	"\n" +
	"\b_enabled\"[\n" +
	"\x16ListRoleTemplatesReply\x12A\n" +
	"\x0erole_templates\x18\x01 \x03(\v2\x1a.iam.grant.v1.RoleTemplateR\rroleTemplates\"\xd6\x02\n" +
	"\x12GrantAccessRequest\x12=\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefB\x03\xe0A\x02R\bresource\x12%\n" +
	"\brole_key\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\aroleKey\x12:\n" +
	"\asubject\x18\x03 \x01(\v2\x1b.iam.resource.v1.SubjectRefB\x03\xe0A\x02R\asubject\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\x90\x01\n" +
	"\x13RevokeAccessRequest\x12%\n" +
	"\bgrant_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\agrantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12:\n" +
	"\x19delete_graph_relationship\x18\x03 \x01(\bR\x17deleteGraphRelationship\"u\n" +
	"\x11RevokeAccessReply\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x18\n" +
	"\arevoked\x18\x02 \x01(\bR\arevoked\x12+\n" +
	"\x11consistency_token\x18\x03 \x01(\tR\x10consistencyToken\"\xb7\x02\n" +
	"\x11ListGrantsRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\bresource\x125\n" +
	"\asubject\x18\x02 \x01(\v2\x1b.iam.resource.v1.SubjectRefR\asubject\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x19\n" +
	"\brole_key\x18\x04 \x01(\tR\aroleKey\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\x06active\x18\x06 \x01(\bH\x00R\x06active\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\b \x01(\tR\tpageTokenB\t\n" +
	"\a_active\"\x85\x01\n" +
	"\x0fListGrantsReply\x12+\n" +
	"\x06grants\x18\x01 \x03(\v2\x13.iam.grant.v1.GrantR\x06grants\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"\xbd\x01\n" +
	"\x14ExplainAccessRequest\x12=\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefB\x03\xe0A\x02R\bresource\x12*\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"permission\x12:\n" +
	"\asubject\x18\x03 \x01(\v2\x1b.iam.resource.v1.SubjectRefB\x03\xe0A\x02R\asubject\"\xca\x01\n" +
	"\vExplainStep\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x128\n" +
	"\bresource\x18\x03 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\bresource\x125\n" +
	"\asubject\x18\x04 \x01(\v2\x1b.iam.resource.v1.SubjectRefR\asubject\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xbc\x01\n" +
	"\x12ExplainAccessReply\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06effect\x18\x02 \x01(\tR\x06effect\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12/\n" +
	"\x05steps\x18\x04 \x03(\v2\x19.iam.grant.v1.ExplainStepR\x05steps\x12+\n" +
	"\x11consistency_token\x18\x05 \x01(\tR\x10consistencyToken2\x8f\x10\n" +
	"\fGrantService\x12\xe7\x01\n" +
	"\x14RegisterRoleTemplate\x12).iam.grant.v1.RegisterRoleTemplateRequest\x1a\x1a.iam.grant.v1.RoleTemplate\"\x87\x01\x92\xf4\x18T\b\x03\x12*\n" +
	"\x06manage\x12\x11iam:role_template\x1a\viam-service \x01\x1a$\b\x01\x12\x1aiam.role_template.register\x1a\x04high\x82\xd3\xe4\x93\x02):\x01*\"$/v1/iam/control-plane/role-templates\x12\xeb\x01\n" +
	"\x12UpdateRoleTemplate\x12'.iam.grant.v1.UpdateRoleTemplateRequest\x1a\x1a.iam.grant.v1.RoleTemplate\"\x8f\x01\x92\xf4\x18W\b\x03\x12/\n" +
	"\x06manage\x12\x16iam:role_template:{id}\x1a\viam-service \x01\x1a\"\b\x01\x12\x18iam.role_template.update\x1a\x04high\x82\xd3\xe4\x93\x02.:\x01*2)/v1/iam/control-plane/role-templates/{id}\x12\xf6\x01\n" +
	"\x13DisableRoleTemplate\x12(.iam.grant.v1.DisableRoleTemplateRequest\x1a\x1a.iam.grant.v1.RoleTemplate\"\x98\x01\x92\xf4\x18X\b\x03\x12/\n" +
	"\x06manage\x12\x16iam:role_template:{id}\x1a\viam-service \x01\x1a#\b\x01\x12\x19iam.role_template.disable\x1a\x04high\x82\xd3\xe4\x93\x026:\x01*\"1/v1/iam/control-plane/role-templates/{id}:disable\x12\xa2\x02\n" +
	"\x19PreviewRoleTemplateImpact\x12..iam.grant.v1.PreviewRoleTemplateImpactRequest\x1a,.iam.grant.v1.PreviewRoleTemplateImpactReply\"\xa6\x01\x92\xf4\x18_\b\x03\x12-\n" +
	"\x04read\x12\x16iam:role_template:{id}\x1a\viam-service \x01\x1a,\b\x01\x12 iam.role_template.preview_impact\x1a\x06medium\x82\xd3\xe4\x93\x02=:\x01*\"8/v1/iam/control-plane/role-templates/{id}:preview-impact\x12\xe4\x01\n" +
	"\x11ListRoleTemplates\x12&.iam.grant.v1.ListRoleTemplatesRequest\x1a$.iam.grant.v1.ListRoleTemplatesReply\"\x80\x01\x92\xf4\x18P\b\x03\x12(\n" +
	"\x04list\x12\x11iam:role_template\x1a\viam-service \x01\x1a\"\b\x01\x12\x16iam.role_template.list\x1a\x06medium\x82\xd3\xe4\x93\x02&\x12$/v1/iam/control-plane/role-templates\x12\xb2\x01\n" +
	"\vGrantAccess\x12 .iam.grant.v1.GrantAccessRequest\x1a\x13.iam.grant.v1.Grant\"l\x92\xf4\x18A\b\x03\x12!\n" +
	"\x05grant\x12\tiam:grant\x1a\viam-service \x01\x1a\x1a\b\x01\x12\x10iam.grant.create\x1a\x04high\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/iam/control-plane/grants\x12\xdf\x01\n" +
	"\fRevokeAccess\x12!.iam.grant.v1.RevokeAccessRequest\x1a\x1f.iam.grant.v1.RevokeAccessReply\"\x8a\x01\x92\xf4\x18M\b\x03\x12-\n" +
	"\x06revoke\x12\x14iam:grant:{grant_id}\x1a\viam-service \x01\x1a\x1a\b\x01\x12\x10iam.grant.revoke\x1a\x04high\x82\xd3\xe4\x93\x023:\x01*\"./v1/iam/control-plane/grants/{grant_id}/revoke\x12\xb6\x01\n" +
	"\n" +
	"ListGrants\x12\x1f.iam.grant.v1.ListGrantsRequest\x1a\x1d.iam.grant.v1.ListGrantsReply\"h\x92\xf4\x18@\b\x03\x12 \n" +
	"\x04list\x12\tiam:grant\x1a\viam-service \x01\x1a\x1a\b\x01\x12\x0eiam.grant.list\x1a\x06medium\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/iam/control-plane/grants\x12\xd1\x01\n" +
	"\rExplainAccess\x12\".iam.grant.v1.ExplainAccessRequest\x1a .iam.grant.v1.ExplainAccessReply\"z\x92\xf4\x18G\b\x03\x12#\n" +
	"\aexplain\x12\tiam:grant\x1a\viam-service \x01\x1a\x1e\b\x01\x12\x12iam.access.explain\x1a\x06medium\x82\xd3\xe4\x93\x02):\x01*\"$/v1/iam/control-plane/access:explainB=Z;github.com/aisphereio/aisphere-iam/api/iam/grant/v1;grantv1b\x06proto3"

var (
	file_iam_grant_v1_grant_proto_rawDescOnce sync.Once
	file_iam_grant_v1_grant_proto_rawDescData []byte
)

func file_iam_grant_v1_grant_proto_rawDescGZIP() []byte {
	file_iam_grant_v1_grant_proto_rawDescOnce.Do(func() {
		file_iam_grant_v1_grant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_grant_v1_grant_proto_rawDesc), len(file_iam_grant_v1_grant_proto_rawDesc)))
	})
	return file_iam_grant_v1_grant_proto_rawDescData
}

var file_iam_grant_v1_grant_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_iam_grant_v1_grant_proto_goTypes = []any{
	(*RoleTemplate)(nil),                     // 0: iam.grant.v1.RoleTemplate
	(*Grant)(nil),                            // 1: iam.grant.v1.Grant
	(*RegisterRoleTemplateRequest)(nil),      // 2: iam.grant.v1.RegisterRoleTemplateRequest
	(*UpdateRoleTemplateRequest)(nil),        // 3: iam.grant.v1.UpdateRoleTemplateRequest
	(*DisableRoleTemplateRequest)(nil),       // 4: iam.grant.v1.DisableRoleTemplateRequest
	(*PreviewRoleTemplateImpactRequest)(nil), // 5: iam.grant.v1.PreviewRoleTemplateImpactRequest
	(*PreviewRoleTemplateImpactReply)(nil),   // 6: iam.grant.v1.PreviewRoleTemplateImpactReply
	(*ListRoleTemplatesRequest)(nil),         // 7: iam.grant.v1.ListRoleTemplatesRequest
	(*ListRoleTemplatesReply)(nil),           // 8: iam.grant.v1.ListRoleTemplatesReply
	(*GrantAccessRequest)(nil),               // 9: iam.grant.v1.GrantAccessRequest
	(*RevokeAccessRequest)(nil),              // 10: iam.grant.v1.RevokeAccessRequest
	(*RevokeAccessReply)(nil),                // 11: iam.grant.v1.RevokeAccessReply
	(*ListGrantsRequest)(nil),                // 12: iam.grant.v1.ListGrantsRequest
	(*ListGrantsReply)(nil),                  // 13: iam.grant.v1.ListGrantsReply
	(*ExplainAccessRequest)(nil),             // 14: iam.grant.v1.ExplainAccessRequest
	(*ExplainStep)(nil),                      // 15: iam.grant.v1.ExplainStep
	(*ExplainAccessReply)(nil),               // 16: iam.grant.v1.ExplainAccessReply
	(*structpb.Struct)(nil),                  // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),            // 18: google.protobuf.Timestamp
	(*v1.ResourceRef)(nil),                   // 19: iam.resource.v1.ResourceRef
	(*v1.SubjectRef)(nil),                    // 20: iam.resource.v1.SubjectRef
}
var file_iam_grant_v1_grant_proto_depIdxs = []int32{
	17, // 0: iam.grant.v1.RoleTemplate.metadata:type_name -> google.protobuf.Struct
	18, // 1: iam.grant.v1.RoleTemplate.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: iam.grant.v1.RoleTemplate.updated_at:type_name -> google.protobuf.Timestamp
	19, // 3: iam.grant.v1.Grant.resource:type_name -> iam.resource.v1.ResourceRef
	20, // 4: iam.grant.v1.Grant.subject:type_name -> iam.resource.v1.SubjectRef
	18, // 5: iam.grant.v1.Grant.expires_at:type_name -> google.protobuf.Timestamp
	20, // 6: iam.grant.v1.Grant.created_by:type_name -> iam.resource.v1.SubjectRef
	18, // 7: iam.grant.v1.Grant.created_at:type_name -> google.protobuf.Timestamp
	18, // 8: iam.grant.v1.Grant.revoked_at:type_name -> google.protobuf.Timestamp
	17, // 9: iam.grant.v1.Grant.metadata:type_name -> google.protobuf.Struct
	0,  // 10: iam.grant.v1.RegisterRoleTemplateRequest.role_template:type_name -> iam.grant.v1.RoleTemplate
	0,  // 11: iam.grant.v1.ListRoleTemplatesReply.role_templates:type_name -> iam.grant.v1.RoleTemplate
	19, // 12: iam.grant.v1.GrantAccessRequest.resource:type_name -> iam.resource.v1.ResourceRef
	20, // 13: iam.grant.v1.GrantAccessRequest.subject:type_name -> iam.resource.v1.SubjectRef
	18, // 14: iam.grant.v1.GrantAccessRequest.expires_at:type_name -> google.protobuf.Timestamp
	17, // 15: iam.grant.v1.GrantAccessRequest.metadata:type_name -> google.protobuf.Struct
	19, // 16: iam.grant.v1.ListGrantsRequest.resource:type_name -> iam.resource.v1.ResourceRef
	20, // 17: iam.grant.v1.ListGrantsRequest.subject:type_name -> iam.resource.v1.SubjectRef
	1,  // 18: iam.grant.v1.ListGrantsReply.grants:type_name -> iam.grant.v1.Grant
	19, // 19: iam.grant.v1.ExplainAccessRequest.resource:type_name -> iam.resource.v1.ResourceRef
	20, // 20: iam.grant.v1.ExplainAccessRequest.subject:type_name -> iam.resource.v1.SubjectRef
	19, // 21: iam.grant.v1.ExplainStep.resource:type_name -> iam.resource.v1.ResourceRef
	20, // 22: iam.grant.v1.ExplainStep.subject:type_name -> iam.resource.v1.SubjectRef
	15, // 23: iam.grant.v1.ExplainAccessReply.steps:type_name -> iam.grant.v1.ExplainStep
	2,  // 24: iam.grant.v1.GrantService.RegisterRoleTemplate:input_type -> iam.grant.v1.RegisterRoleTemplateRequest
	3,  // 25: iam.grant.v1.GrantService.UpdateRoleTemplate:input_type -> iam.grant.v1.UpdateRoleTemplateRequest
	4,  // 26: iam.grant.v1.GrantService.DisableRoleTemplate:input_type -> iam.grant.v1.DisableRoleTemplateRequest
	5,  // 27: iam.grant.v1.GrantService.PreviewRoleTemplateImpact:input_type -> iam.grant.v1.PreviewRoleTemplateImpactRequest
	7,  // 28: iam.grant.v1.GrantService.ListRoleTemplates:input_type -> iam.grant.v1.ListRoleTemplatesRequest
	9,  // 29: iam.grant.v1.GrantService.GrantAccess:input_type -> iam.grant.v1.GrantAccessRequest
	10, // 30: iam.grant.v1.GrantService.RevokeAccess:input_type -> iam.grant.v1.RevokeAccessRequest
	12, // 31: iam.grant.v1.GrantService.ListGrants:input_type -> iam.grant.v1.ListGrantsRequest
	14, // 32: iam.grant.v1.GrantService.ExplainAccess:input_type -> iam.grant.v1.ExplainAccessRequest
	0,  // 33: iam.grant.v1.GrantService.RegisterRoleTemplate:output_type -> iam.grant.v1.RoleTemplate
	0,  // 34: iam.grant.v1.GrantService.UpdateRoleTemplate:output_type -> iam.grant.v1.RoleTemplate
	0,  // 35: iam.grant.v1.GrantService.DisableRoleTemplate:output_type -> iam.grant.v1.RoleTemplate
	6,  // 36: iam.grant.v1.GrantService.PreviewRoleTemplateImpact:output_type -> iam.grant.v1.PreviewRoleTemplateImpactReply
	8,  // 37: iam.grant.v1.GrantService.ListRoleTemplates:output_type -> iam.grant.v1.ListRoleTemplatesReply
	1,  // 38: iam.grant.v1.GrantService.GrantAccess:output_type -> iam.grant.v1.Grant
	11, // 39: iam.grant.v1.GrantService.RevokeAccess:output_type -> iam.grant.v1.RevokeAccessReply
	13, // 40: iam.grant.v1.GrantService.ListGrants:output_type -> iam.grant.v1.ListGrantsReply
	16, // 41: iam.grant.v1.GrantService.ExplainAccess:output_type -> iam.grant.v1.ExplainAccessReply
	33, // [33:42] is the sub-list for method output_type
	24, // [24:33] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_iam_grant_v1_grant_proto_init() }
func file_iam_grant_v1_grant_proto_init() {
	if File_iam_grant_v1_grant_proto != nil {
		return
	}
	file_iam_grant_v1_grant_proto_msgTypes[7].OneofWrappers = []any{}
	file_iam_grant_v1_grant_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_grant_v1_grant_proto_rawDesc), len(file_iam_grant_v1_grant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_grant_v1_grant_proto_goTypes,
		DependencyIndexes: file_iam_grant_v1_grant_proto_depIdxs,
		MessageInfos:      file_iam_grant_v1_grant_proto_msgTypes,
	}.Build()
	File_iam_grant_v1_grant_proto = out.File
	file_iam_grant_v1_grant_proto_goTypes = nil
	file_iam_grant_v1_grant_proto_depIdxs = nil
}
