// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.9
// source: iam/project/v1/project.proto

package projectv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// ProjectServiceKernelModule returns the generated Kernel service module for iam.project.v1.ProjectService.
func ProjectServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "project-service",
		GatewayManifest:     ProjectServiceGatewayManifest(),
		RequestInfoResolver: ProjectServiceKernelRequestInfoResolver,
		AccessResolver:      ProjectServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(ProjectServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.project.v1.ProjectService must implement ProjectServiceServer, got %T", impl)
			}
			RegisterProjectServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(ProjectServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.project.v1.ProjectService must implement ProjectServiceHTTPServer, got %T", impl)
			}
			RegisterProjectServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(ProjectServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.project.v1.ProjectService must implement ProjectServiceClient, got %T", client)
			}
			return RegisterProjectServiceGatewayInvokers(r, typed)
		},
	}
}

var ProjectServiceKernelAuthzRules = authz.Rules{
	"/iam.project.v1.ProjectService/CreateProject": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "CreateProject",
		FullMethod: "/iam.project.v1.ProjectService/CreateProject",
		Action:     "create_project",
		Resource:   "iam:project",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project.create",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/GetProject": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "GetProject",
		FullMethod: "/iam.project.v1.ProjectService/GetProject",
		Action:     "read",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project.get",
		AuditRisk:  "low",
	},
	"/iam.project.v1.ProjectService/ListProjects": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "ListProjects",
		FullMethod: "/iam.project.v1.ProjectService/ListProjects",
		Action:     "list",
		Resource:   "project:*",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project.list",
		AuditRisk:  "medium",
	},
	"/iam.project.v1.ProjectService/UpdateProject": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "UpdateProject",
		FullMethod: "/iam.project.v1.ProjectService/UpdateProject",
		Action:     "manage",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project.update",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/ArchiveProject": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "ArchiveProject",
		FullMethod: "/iam.project.v1.ProjectService/ArchiveProject",
		Action:     "manage",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project.archive",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/RegisterCapability": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "RegisterCapability",
		FullMethod: "/iam.project.v1.ProjectService/RegisterCapability",
		Action:     "manage",
		Resource:   "iam:capability",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.capability.register",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/ListCapabilities": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "ListCapabilities",
		FullMethod: "/iam.project.v1.ProjectService/ListCapabilities",
		Action:     "list",
		Resource:   "iam:capability",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.capability.list",
		AuditRisk:  "medium",
	},
	"/iam.project.v1.ProjectService/EnableProjectCapability": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "EnableProjectCapability",
		FullMethod: "/iam.project.v1.ProjectService/EnableProjectCapability",
		Action:     "manage",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project_capability.enable",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/DisableProjectCapability": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "DisableProjectCapability",
		FullMethod: "/iam.project.v1.ProjectService/DisableProjectCapability",
		Action:     "manage",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project_capability.disable",
		AuditRisk:  "high",
	},
	"/iam.project.v1.ProjectService/ListProjectCapabilities": {
		Service:    "iam.project.v1.ProjectService",
		Method:     "ListProjectCapabilities",
		FullMethod: "/iam.project.v1.ProjectService/ListProjectCapabilities",
		Action:     "read",
		Resource:   "project:{project_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.project_capability.list",
		AuditRisk:  "medium",
	},
}

// ProjectServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func ProjectServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _ProjectServiceKernelNormalizeOperation(operation) {
	case "/iam.project.v1.ProjectService/CreateProject":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "CreateProject",
			Operation:     "/iam.project.v1.ProjectService/CreateProject",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "create_project",
			Resource:      "iam:project",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/GetProject":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "GetProject",
			Operation:     "/iam.project.v1.ProjectService/GetProject",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/ListProjects":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "ListProjects",
			Operation:     "/iam.project.v1.ProjectService/ListProjects",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "list",
			Resource:      "project:*",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/UpdateProject":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "UpdateProject",
			Operation:     "/iam.project.v1.ProjectService/UpdateProject",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project.update"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/ArchiveProject":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "ArchiveProject",
			Operation:     "/iam.project.v1.ProjectService/ArchiveProject",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project.archive"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/RegisterCapability":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "RegisterCapability",
			Operation:     "/iam.project.v1.ProjectService/RegisterCapability",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "iam:capability",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.capability.register"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/ListCapabilities":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "ListCapabilities",
			Operation:     "/iam.project.v1.ProjectService/ListCapabilities",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "list",
			Resource:      "iam:capability",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.capability.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/EnableProjectCapability":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "EnableProjectCapability",
			Operation:     "/iam.project.v1.ProjectService/EnableProjectCapability",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project_capability.enable"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/DisableProjectCapability":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "DisableProjectCapability",
			Operation:     "/iam.project.v1.ProjectService/DisableProjectCapability",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project_capability.disable"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.project.v1.ProjectService/ListProjectCapabilities":
		info := requestx.Info{
			Service:       "iam.project.v1.ProjectService",
			Method:        "ListProjectCapabilities",
			Operation:     "/iam.project.v1.ProjectService/ListProjectCapabilities",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "project:{project_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.project_capability.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// ProjectServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func ProjectServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := ProjectServiceKernelAuthzRules[_ProjectServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _ProjectServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CreateProject", "iam.project.v1.ProjectService/CreateProject":
		return "/iam.project.v1.ProjectService/CreateProject"
	case "GetProject", "iam.project.v1.ProjectService/GetProject":
		return "/iam.project.v1.ProjectService/GetProject"
	case "ListProjects", "iam.project.v1.ProjectService/ListProjects":
		return "/iam.project.v1.ProjectService/ListProjects"
	case "UpdateProject", "iam.project.v1.ProjectService/UpdateProject":
		return "/iam.project.v1.ProjectService/UpdateProject"
	case "ArchiveProject", "iam.project.v1.ProjectService/ArchiveProject":
		return "/iam.project.v1.ProjectService/ArchiveProject"
	case "RegisterCapability", "iam.project.v1.ProjectService/RegisterCapability":
		return "/iam.project.v1.ProjectService/RegisterCapability"
	case "ListCapabilities", "iam.project.v1.ProjectService/ListCapabilities":
		return "/iam.project.v1.ProjectService/ListCapabilities"
	case "EnableProjectCapability", "iam.project.v1.ProjectService/EnableProjectCapability":
		return "/iam.project.v1.ProjectService/EnableProjectCapability"
	case "DisableProjectCapability", "iam.project.v1.ProjectService/DisableProjectCapability":
		return "/iam.project.v1.ProjectService/DisableProjectCapability"
	case "ListProjectCapabilities", "iam.project.v1.ProjectService/ListProjectCapabilities":
		return "/iam.project.v1.ProjectService/ListProjectCapabilities"
	default:
		return operation
	}
}
