// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.0
// - protoc             (unknown)
// source: iam/project/v1/project.proto

package projectv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationProjectServiceArchiveOrganization = "/iam.project.v1.ProjectService/ArchiveOrganization"
const OperationProjectServiceArchiveProject = "/iam.project.v1.ProjectService/ArchiveProject"
const OperationProjectServiceCreateOrganization = "/iam.project.v1.ProjectService/CreateOrganization"
const OperationProjectServiceCreateProject = "/iam.project.v1.ProjectService/CreateProject"
const OperationProjectServiceDisableProjectCapability = "/iam.project.v1.ProjectService/DisableProjectCapability"
const OperationProjectServiceEnableProjectCapability = "/iam.project.v1.ProjectService/EnableProjectCapability"
const OperationProjectServiceGetOrganization = "/iam.project.v1.ProjectService/GetOrganization"
const OperationProjectServiceGetProject = "/iam.project.v1.ProjectService/GetProject"
const OperationProjectServiceListCapabilities = "/iam.project.v1.ProjectService/ListCapabilities"
const OperationProjectServiceListOrganizations = "/iam.project.v1.ProjectService/ListOrganizations"
const OperationProjectServiceListProjectCapabilities = "/iam.project.v1.ProjectService/ListProjectCapabilities"
const OperationProjectServiceListProjects = "/iam.project.v1.ProjectService/ListProjects"
const OperationProjectServiceRegisterCapability = "/iam.project.v1.ProjectService/RegisterCapability"
const OperationProjectServiceUpdateOrganization = "/iam.project.v1.ProjectService/UpdateOrganization"
const OperationProjectServiceUpdateProject = "/iam.project.v1.ProjectService/UpdateProject"

type ProjectServiceHTTPServer interface {
	ArchiveOrganization(context.Context, *ArchiveOrganizationRequest) (*Organization, error)
	ArchiveProject(context.Context, *ArchiveProjectRequest) (*Project, error)
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*Organization, error)
	CreateProject(context.Context, *CreateProjectRequest) (*Project, error)
	DisableProjectCapability(context.Context, *DisableProjectCapabilityRequest) (*ProjectCapability, error)
	EnableProjectCapability(context.Context, *EnableProjectCapabilityRequest) (*ProjectCapability, error)
	GetOrganization(context.Context, *GetOrganizationRequest) (*Organization, error)
	GetProject(context.Context, *GetProjectRequest) (*Project, error)
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesReply, error)
	ListOrganizations(context.Context, *ListOrganizationsRequest) (*ListOrganizationsReply, error)
	ListProjectCapabilities(context.Context, *ListProjectCapabilitiesRequest) (*ListProjectCapabilitiesReply, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsReply, error)
	RegisterCapability(context.Context, *RegisterCapabilityRequest) (*Capability, error)
	UpdateOrganization(context.Context, *UpdateOrganizationRequest) (*Organization, error)
	UpdateProject(context.Context, *UpdateProjectRequest) (*Project, error)
}

func RegisterProjectServiceHTTPServer(s *http.Server, srv ProjectServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/iam/control-plane/capabilities", _ProjectService_ListCapabilities0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/orgs", _ProjectService_ListOrganizations0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/projects", _ProjectService_ListProjects0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/projects/{project_id}/capabilities", _ProjectService_ListProjectCapabilities0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/orgs/{org_id}", _ProjectService_GetOrganization0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/iam/control-plane/projects/{project_id}", _ProjectService_GetProject0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/iam/control-plane/orgs/{org_id}", _ProjectService_UpdateOrganization0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/iam/control-plane/projects/{project_id}", _ProjectService_UpdateProject0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/capabilities", _ProjectService_RegisterCapability0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/orgs", _ProjectService_CreateOrganization0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/orgs/{org_id}/archive", _ProjectService_ArchiveOrganization0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/orgs/{org_id}/projects", _ProjectService_CreateProject0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/projects/{project_id}/archive", _ProjectService_ArchiveProject0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/projects/{project_id}/capabilities/{capability_id}:disable", _ProjectService_DisableProjectCapability0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/control-plane/projects/{project_id}/capabilities/{capability_id}:enable", _ProjectService_EnableProjectCapability0_HTTP_Handler(srv))
}

func _ProjectService_ListCapabilities0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCapabilitiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListCapabilities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCapabilitiesReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ListOrganizations0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListOrganizationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListOrganizations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListOrganizations(ctx, req.(*ListOrganizationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListOrganizationsReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ListProjects0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProjectsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListProjects)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProjects(ctx, req.(*ListProjectsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectsReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ListProjectCapabilities0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListProjectCapabilitiesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceListProjectCapabilities)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListProjectCapabilities(ctx, req.(*ListProjectCapabilitiesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListProjectCapabilitiesReply)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_GetOrganization0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetOrganizationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceGetOrganization)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetOrganization(ctx, req.(*GetOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_GetProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetProjectRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceGetProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetProject(ctx, req.(*GetProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_UpdateOrganization0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateOrganizationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceUpdateOrganization)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateOrganization(ctx, req.(*UpdateOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_UpdateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceUpdateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProject(ctx, req.(*UpdateProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_RegisterCapability0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RegisterCapabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceRegisterCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterCapability(ctx, req.(*RegisterCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Capability)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_CreateOrganization0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateOrganizationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceCreateOrganization)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateOrganization(ctx, req.(*CreateOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ArchiveOrganization0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArchiveOrganizationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceArchiveOrganization)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ArchiveOrganization(ctx, req.(*ArchiveOrganizationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Organization)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_CreateProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceCreateProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProject(ctx, req.(*CreateProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_ArchiveProject0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ArchiveProjectRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceArchiveProject)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ArchiveProject(ctx, req.(*ArchiveProjectRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Project)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_DisableProjectCapability0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DisableProjectCapabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceDisableProjectCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisableProjectCapability(ctx, req.(*DisableProjectCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectCapability)
		return ctx.Result(200, reply)
	}
}

func _ProjectService_EnableProjectCapability0_HTTP_Handler(srv ProjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EnableProjectCapabilityRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProjectServiceEnableProjectCapability)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EnableProjectCapability(ctx, req.(*EnableProjectCapabilityRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ProjectCapability)
		return ctx.Result(200, reply)
	}
}

type ProjectServiceHTTPClient interface {
	ArchiveOrganization(ctx context.Context, req *ArchiveOrganizationRequest, opts ...http.CallOption) (rsp *Organization, err error)
	ArchiveProject(ctx context.Context, req *ArchiveProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
	CreateOrganization(ctx context.Context, req *CreateOrganizationRequest, opts ...http.CallOption) (rsp *Organization, err error)
	CreateProject(ctx context.Context, req *CreateProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
	DisableProjectCapability(ctx context.Context, req *DisableProjectCapabilityRequest, opts ...http.CallOption) (rsp *ProjectCapability, err error)
	EnableProjectCapability(ctx context.Context, req *EnableProjectCapabilityRequest, opts ...http.CallOption) (rsp *ProjectCapability, err error)
	GetOrganization(ctx context.Context, req *GetOrganizationRequest, opts ...http.CallOption) (rsp *Organization, err error)
	GetProject(ctx context.Context, req *GetProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
	ListCapabilities(ctx context.Context, req *ListCapabilitiesRequest, opts ...http.CallOption) (rsp *ListCapabilitiesReply, err error)
	ListOrganizations(ctx context.Context, req *ListOrganizationsRequest, opts ...http.CallOption) (rsp *ListOrganizationsReply, err error)
	ListProjectCapabilities(ctx context.Context, req *ListProjectCapabilitiesRequest, opts ...http.CallOption) (rsp *ListProjectCapabilitiesReply, err error)
	ListProjects(ctx context.Context, req *ListProjectsRequest, opts ...http.CallOption) (rsp *ListProjectsReply, err error)
	RegisterCapability(ctx context.Context, req *RegisterCapabilityRequest, opts ...http.CallOption) (rsp *Capability, err error)
	UpdateOrganization(ctx context.Context, req *UpdateOrganizationRequest, opts ...http.CallOption) (rsp *Organization, err error)
	UpdateProject(ctx context.Context, req *UpdateProjectRequest, opts ...http.CallOption) (rsp *Project, err error)
}

type ProjectServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewProjectServiceHTTPClient(client *http.Client) ProjectServiceHTTPClient {
	return &ProjectServiceHTTPClientImpl{client}
}

func (c *ProjectServiceHTTPClientImpl) ArchiveOrganization(ctx context.Context, in *ArchiveOrganizationRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/iam/control-plane/orgs/{org_id}/archive"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceArchiveOrganization),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ArchiveProject(ctx context.Context, in *ArchiveProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/v1/iam/control-plane/projects/{project_id}/archive"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceArchiveProject),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/iam/control-plane/orgs"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceCreateOrganization),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) CreateProject(ctx context.Context, in *CreateProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/v1/iam/control-plane/orgs/{org_id}/projects"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceCreateProject),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) DisableProjectCapability(ctx context.Context, in *DisableProjectCapabilityRequest, opts ...http.CallOption) (*ProjectCapability, error) {
	var out ProjectCapability
	pattern := "/v1/iam/control-plane/projects/{project_id}/capabilities/{capability_id}:disable"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceDisableProjectCapability),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) EnableProjectCapability(ctx context.Context, in *EnableProjectCapabilityRequest, opts ...http.CallOption) (*ProjectCapability, error) {
	var out ProjectCapability
	pattern := "/v1/iam/control-plane/projects/{project_id}/capabilities/{capability_id}:enable"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceEnableProjectCapability),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) GetOrganization(ctx context.Context, in *GetOrganizationRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/iam/control-plane/orgs/{org_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceGetOrganization),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) GetProject(ctx context.Context, in *GetProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/v1/iam/control-plane/projects/{project_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceGetProject),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...http.CallOption) (*ListCapabilitiesReply, error) {
	var out ListCapabilitiesReply
	pattern := "/v1/iam/control-plane/capabilities"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceListCapabilities),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListOrganizations(ctx context.Context, in *ListOrganizationsRequest, opts ...http.CallOption) (*ListOrganizationsReply, error) {
	var out ListOrganizationsReply
	pattern := "/v1/iam/control-plane/orgs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceListOrganizations),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListProjectCapabilities(ctx context.Context, in *ListProjectCapabilitiesRequest, opts ...http.CallOption) (*ListProjectCapabilitiesReply, error) {
	var out ListProjectCapabilitiesReply
	pattern := "/v1/iam/control-plane/projects/{project_id}/capabilities"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceListProjectCapabilities),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...http.CallOption) (*ListProjectsReply, error) {
	var out ListProjectsReply
	pattern := "/v1/iam/control-plane/projects"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationProjectServiceListProjects),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) RegisterCapability(ctx context.Context, in *RegisterCapabilityRequest, opts ...http.CallOption) (*Capability, error) {
	var out Capability
	pattern := "/v1/iam/control-plane/capabilities"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceRegisterCapability),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) UpdateOrganization(ctx context.Context, in *UpdateOrganizationRequest, opts ...http.CallOption) (*Organization, error) {
	var out Organization
	pattern := "/v1/iam/control-plane/orgs/{org_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceUpdateOrganization),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ProjectServiceHTTPClientImpl) UpdateProject(ctx context.Context, in *UpdateProjectRequest, opts ...http.CallOption) (*Project, error) {
	var out Project
	pattern := "/v1/iam/control-plane/projects/{project_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationProjectServiceUpdateProject),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
