// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway v0.4.9
// source: iam/project/v1/project.proto

package projectv1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

func ProjectServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "project-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "project.create.project",
				Method:   "POST",
				Path:     "/v1/iam/orgs/{org_id}/projects",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/CreateProject"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.get.project",
				Method:   "GET",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/GetProject"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.list.projects",
				Method:   "GET",
				Path:     "/v1/iam/orgs/{org_id}/projects",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/ListProjects"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.update.project",
				Method:   "PATCH",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/UpdateProject"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.archive.project",
				Method:   "POST",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}/archive",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/ArchiveProject"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.register.capability",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/capabilities",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/RegisterCapability"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.list.capabilities",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/capabilities",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/ListCapabilities"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.enable.project.capability",
				Method:   "POST",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}/capabilities/{capability_id}:enable",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/EnableProjectCapability"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.disable.project.capability",
				Method:   "POST",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}/capabilities/{capability_id}:disable",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/DisableProjectCapability"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
			{
				ID:       "project.list.project.capabilities",
				Method:   "GET",
				Path:     "/v1/iam/orgs/{org_id}/projects/{project_id}/capabilities",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.project.v1.ProjectService/ListProjectCapabilities"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
		},
	}
}

func ProjectServiceGatewayBindCreateProject(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*CreateProjectRequest, error) {
	out := &CreateProjectRequest{}
	if v, ok := req.Body.(*CreateProjectRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(CreateProjectRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindGetProject(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetProjectRequest, error) {
	out := &GetProjectRequest{}
	if v, ok := req.Body.(*GetProjectRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetProjectRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindListProjects(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListProjectsRequest, error) {
	out := &ListProjectsRequest{}
	if v, ok := req.Body.(*ListProjectsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListProjectsRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindUpdateProject(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpdateProjectRequest, error) {
	out := &UpdateProjectRequest{}
	if v, ok := req.Body.(*UpdateProjectRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpdateProjectRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindArchiveProject(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ArchiveProjectRequest, error) {
	out := &ArchiveProjectRequest{}
	if v, ok := req.Body.(*ArchiveProjectRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ArchiveProjectRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindRegisterCapability(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*RegisterCapabilityRequest, error) {
	out := &RegisterCapabilityRequest{}
	if v, ok := req.Body.(*RegisterCapabilityRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(RegisterCapabilityRequest); ok {
		out = &v
	}
	return out, nil
}

func ProjectServiceGatewayBindListCapabilities(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListCapabilitiesRequest, error) {
	out := &ListCapabilitiesRequest{}
	if v, ok := req.Body.(*ListCapabilitiesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListCapabilitiesRequest); ok {
		out = &v
	}
	return out, nil
}

func ProjectServiceGatewayBindEnableProjectCapability(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*EnableProjectCapabilityRequest, error) {
	out := &EnableProjectCapabilityRequest{}
	if v, ok := req.Body.(*EnableProjectCapabilityRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(EnableProjectCapabilityRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	if v := match.Params["capability_id"]; v != "" {
		out.CapabilityId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindDisableProjectCapability(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DisableProjectCapabilityRequest, error) {
	out := &DisableProjectCapabilityRequest{}
	if v, ok := req.Body.(*DisableProjectCapabilityRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DisableProjectCapabilityRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	if v := match.Params["capability_id"]; v != "" {
		out.CapabilityId = v
	}
	return out, nil
}

func ProjectServiceGatewayBindListProjectCapabilities(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListProjectCapabilitiesRequest, error) {
	out := &ListProjectCapabilitiesRequest{}
	if v, ok := req.Body.(*ListProjectCapabilitiesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListProjectCapabilitiesRequest); ok {
		out = &v
	}
	if v := match.Params["org_id"]; v != "" {
		out.OrgId = v
	}
	if v := match.Params["project_id"]; v != "" {
		out.ProjectId = v
	}
	return out, nil
}

func RegisterProjectServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client ProjectServiceClient) error {
	if err := registry.Register("/iam.project.v1.ProjectService/CreateProject", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindCreateProject, client.CreateProject)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/GetProject", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindGetProject, client.GetProject)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/ListProjects", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindListProjects, client.ListProjects)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/UpdateProject", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindUpdateProject, client.UpdateProject)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/ArchiveProject", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindArchiveProject, client.ArchiveProject)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/RegisterCapability", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindRegisterCapability, client.RegisterCapability)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/ListCapabilities", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindListCapabilities, client.ListCapabilities)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/EnableProjectCapability", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindEnableProjectCapability, client.EnableProjectCapability)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/DisableProjectCapability", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindDisableProjectCapability, client.DisableProjectCapability)); err != nil {
		return err
	}
	if err := registry.Register("/iam.project.v1.ProjectService/ListProjectCapabilities", gatewayx.GRPCUnaryInvoker(ProjectServiceGatewayBindListProjectCapabilities, client.ListProjectCapabilities)); err != nil {
		return err
	}
	return nil
}
