// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.17
// - protoc             (unknown)
// source: iam/access/v1/access_query.proto

package accessv1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAccessQueryServiceListResourceAccess = "/iam.access.v1.AccessQueryService/ListResourceAccess"
const OperationAccessQueryServiceListSubjectEntitlements = "/iam.access.v1.AccessQueryService/ListSubjectEntitlements"
const OperationAccessQueryServicePreviewGrant = "/iam.access.v1.AccessQueryService/PreviewGrant"

type AccessQueryServiceHTTPServer interface {
	// ListResourceAccess ListResourceAccess returns all subjects that have effective permissions
	// on a given resource, including inherited access.
	ListResourceAccess(context.Context, *ListResourceAccessRequest) (*ListResourceAccessReply, error)
	// ListSubjectEntitlements ListSubjectEntitlements returns all effective permissions for a subject
	// across all resources, including inherited permissions from groups,
	// parent resources, zone-level, and platform-level grants.
	ListSubjectEntitlements(context.Context, *ListSubjectEntitlementsRequest) (*ListSubjectEntitlementsReply, error)
	// PreviewGrant PreviewGrant checks what permissions a subject would receive if granted
	// a given role on a resource, without actually creating the grant.
	PreviewGrant(context.Context, *PreviewGrantRequest) (*PreviewGrantReply, error)
}

func RegisterAccessQueryServiceHTTPServer(s *http.Server, srv AccessQueryServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/iam/orgs/{org_id}/access:preview-grant", _AccessQueryService_PreviewGrant0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/access:resource-access", _AccessQueryService_ListResourceAccess0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/access:subject-entitlements", _AccessQueryService_ListSubjectEntitlements0_HTTP_Handler(srv))
}

func _AccessQueryService_PreviewGrant0_HTTP_Handler(srv AccessQueryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewGrantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessQueryServicePreviewGrant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewGrant(ctx, req.(*PreviewGrantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewGrantReply)
		return ctx.Result(200, reply)
	}
}

func _AccessQueryService_ListResourceAccess0_HTTP_Handler(srv AccessQueryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListResourceAccessRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessQueryServiceListResourceAccess)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListResourceAccess(ctx, req.(*ListResourceAccessRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListResourceAccessReply)
		return ctx.Result(200, reply)
	}
}

func _AccessQueryService_ListSubjectEntitlements0_HTTP_Handler(srv AccessQueryServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubjectEntitlementsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAccessQueryServiceListSubjectEntitlements)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubjectEntitlements(ctx, req.(*ListSubjectEntitlementsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubjectEntitlementsReply)
		return ctx.Result(200, reply)
	}
}

type AccessQueryServiceHTTPClient interface {
	// ListResourceAccess ListResourceAccess returns all subjects that have effective permissions
	// on a given resource, including inherited access.
	ListResourceAccess(ctx context.Context, req *ListResourceAccessRequest, opts ...http.CallOption) (rsp *ListResourceAccessReply, err error)
	// ListSubjectEntitlements ListSubjectEntitlements returns all effective permissions for a subject
	// across all resources, including inherited permissions from groups,
	// parent resources, zone-level, and platform-level grants.
	ListSubjectEntitlements(ctx context.Context, req *ListSubjectEntitlementsRequest, opts ...http.CallOption) (rsp *ListSubjectEntitlementsReply, err error)
	// PreviewGrant PreviewGrant checks what permissions a subject would receive if granted
	// a given role on a resource, without actually creating the grant.
	PreviewGrant(ctx context.Context, req *PreviewGrantRequest, opts ...http.CallOption) (rsp *PreviewGrantReply, err error)
}

type AccessQueryServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAccessQueryServiceHTTPClient(client *http.Client) AccessQueryServiceHTTPClient {
	return &AccessQueryServiceHTTPClientImpl{client}
}

// ListResourceAccess ListResourceAccess returns all subjects that have effective permissions
// on a given resource, including inherited access.
func (c *AccessQueryServiceHTTPClientImpl) ListResourceAccess(ctx context.Context, in *ListResourceAccessRequest, opts ...http.CallOption) (*ListResourceAccessReply, error) {
	var out ListResourceAccessReply
	pattern := "/v1/iam/orgs/{org_id}/access:resource-access"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccessQueryServiceListResourceAccess),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSubjectEntitlements ListSubjectEntitlements returns all effective permissions for a subject
// across all resources, including inherited permissions from groups,
// parent resources, zone-level, and platform-level grants.
func (c *AccessQueryServiceHTTPClientImpl) ListSubjectEntitlements(ctx context.Context, in *ListSubjectEntitlementsRequest, opts ...http.CallOption) (*ListSubjectEntitlementsReply, error) {
	var out ListSubjectEntitlementsReply
	pattern := "/v1/iam/orgs/{org_id}/access:subject-entitlements"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccessQueryServiceListSubjectEntitlements),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreviewGrant PreviewGrant checks what permissions a subject would receive if granted
// a given role on a resource, without actually creating the grant.
func (c *AccessQueryServiceHTTPClientImpl) PreviewGrant(ctx context.Context, in *PreviewGrantRequest, opts ...http.CallOption) (*PreviewGrantReply, error) {
	var out PreviewGrantReply
	pattern := "/v1/iam/orgs/{org_id}/access:preview-grant"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAccessQueryServicePreviewGrant),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
