// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.17
// source: iam/access/v1/access_query.proto

package accessv1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// AccessQueryServiceKernelModule returns the generated Kernel service module for iam.access.v1.AccessQueryService.
func AccessQueryServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "access.query-service",
		GatewayManifest:     AccessQueryServiceGatewayManifest(),
		RequestInfoResolver: AccessQueryServiceKernelRequestInfoResolver,
		AccessResolver:      AccessQueryServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(AccessQueryServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.access.v1.AccessQueryService must implement AccessQueryServiceServer, got %T", impl)
			}
			RegisterAccessQueryServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(AccessQueryServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.access.v1.AccessQueryService must implement AccessQueryServiceHTTPServer, got %T", impl)
			}
			RegisterAccessQueryServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(AccessQueryServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.access.v1.AccessQueryService must implement AccessQueryServiceClient, got %T", client)
			}
			return RegisterAccessQueryServiceGatewayInvokers(r, typed)
		},
	}
}

var AccessQueryServiceKernelAuthzRules = authz.Rules{
	"/iam.access.v1.AccessQueryService/ListSubjectEntitlements": {
		Service:    "iam.access.v1.AccessQueryService",
		Method:     "ListSubjectEntitlements",
		FullMethod: "/iam.access.v1.AccessQueryService/ListSubjectEntitlements",
		Action:     "read",
		Resource:   "iam:access_query",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.access_query.subject_entitlements",
		AuditRisk:  "medium",
	},
	"/iam.access.v1.AccessQueryService/ListResourceAccess": {
		Service:    "iam.access.v1.AccessQueryService",
		Method:     "ListResourceAccess",
		FullMethod: "/iam.access.v1.AccessQueryService/ListResourceAccess",
		Action:     "read",
		Resource:   "iam:access_query",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.access_query.resource_access",
		AuditRisk:  "medium",
	},
	"/iam.access.v1.AccessQueryService/PreviewGrant": {
		Service:    "iam.access.v1.AccessQueryService",
		Method:     "PreviewGrant",
		FullMethod: "/iam.access.v1.AccessQueryService/PreviewGrant",
		Action:     "read",
		Resource:   "iam:access_query",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.access_query.preview_grant",
		AuditRisk:  "low",
	},
}

// AccessQueryServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func AccessQueryServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _AccessQueryServiceKernelNormalizeOperation(operation) {
	case "/iam.access.v1.AccessQueryService/ListSubjectEntitlements":
		info := requestx.Info{
			Service:       "iam.access.v1.AccessQueryService",
			Method:        "ListSubjectEntitlements",
			Operation:     "/iam.access.v1.AccessQueryService/ListSubjectEntitlements",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "iam:access_query",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.access_query.subject_entitlements"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.access.v1.AccessQueryService/ListResourceAccess":
		info := requestx.Info{
			Service:       "iam.access.v1.AccessQueryService",
			Method:        "ListResourceAccess",
			Operation:     "/iam.access.v1.AccessQueryService/ListResourceAccess",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "iam:access_query",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.access_query.resource_access"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.access.v1.AccessQueryService/PreviewGrant":
		info := requestx.Info{
			Service:       "iam.access.v1.AccessQueryService",
			Method:        "PreviewGrant",
			Operation:     "/iam.access.v1.AccessQueryService/PreviewGrant",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "read",
			Resource:      "iam:access_query",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.access_query.preview_grant"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// AccessQueryServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func AccessQueryServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := AccessQueryServiceKernelAuthzRules[_AccessQueryServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _AccessQueryServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "ListSubjectEntitlements", "iam.access.v1.AccessQueryService/ListSubjectEntitlements":
		return "/iam.access.v1.AccessQueryService/ListSubjectEntitlements"
	case "ListResourceAccess", "iam.access.v1.AccessQueryService/ListResourceAccess":
		return "/iam.access.v1.AccessQueryService/ListResourceAccess"
	case "PreviewGrant", "iam.access.v1.AccessQueryService/PreviewGrant":
		return "/iam.access.v1.AccessQueryService/PreviewGrant"
	default:
		return operation
	}
}
