package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	servicePattern  = regexp.MustCompile(`\bservice\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{`)
	rpcPattern      = regexp.MustCompile(`\brpc\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*returns\s*\([^)]*\)\s*\{`)
	exposurePattern = regexp.MustCompile(`\bexposure\s*:\s*([A-Za-z_][A-Za-z0-9_]*)`)
	httpPattern     = regexp.MustCompile(`\b(get|post|put|patch|delete)\s*:\s*"([^"]+)"`)
	pathVariable    = regexp.MustCompile(`\{[^}]+\}`)
)

type routeKey struct {
	Method string
	Path   string
}

type routePolicy struct {
	Exposure string
	Service  string
	RPC      string
}

type contractLock struct {
	Version   int          `json:"version"`
	Source    string       `json:"source"`
	Generator string       `json:"generator"`
	Full      contractHash `json:"full"`
	Console   contractHash `json:"console"`
}

type contractHash struct {
	File   string `json:"file"`
	SHA256 string `json:"sha256"`
}

func main() {
	var (
		input         = flag.String("input", "docs/openapi/aisphere.swagger.json", "merged Swagger input generated by protoc-gen-openapiv2")
		apiRoot       = flag.String("api-root", "api", "root directory containing API proto files")
		fullOutput    = flag.String("full-output", "docs/openapi/iam.full.swagger.json", "full contract output")
		consoleOutput = flag.String("console-output", "docs/openapi/iam.console.swagger.json", "console-safe contract output")
		lockOutput    = flag.String("lock-output", "docs/openapi/openapi.lock.json", "deterministic contract lock output")
		check         = flag.Bool("check", false, "verify outputs are current without rewriting them")
	)
	flag.Parse()

	if err := run(*input, *apiRoot, *fullOutput, *consoleOutput, *lockOutput, *check); err != nil {
		fmt.Fprintln(os.Stderr, "openapi-contract:", err)
		os.Exit(1)
	}
}

func run(input, apiRoot, fullOutput, consoleOutput, lockOutput string, check bool) error {
	raw, err := os.ReadFile(input)
	if err != nil {
		return fmt.Errorf("read generated OpenAPI %q: %w", input, err)
	}

	var full map[string]any
	if err := json.Unmarshal(raw, &full); err != nil {
		return fmt.Errorf("decode generated OpenAPI: %w", err)
	}
	if _, ok := full["paths"].(map[string]any); !ok {
		return errors.New("generated OpenAPI does not contain a paths object")
	}

	policies, err := collectRoutePolicies(apiRoot)
	if err != nil {
		return err
	}

	full["x-aisphere-contract"] = map[string]any{
		"audience": "platform-internal",
		"source":   "protobuf",
	}
	fullBytes, err := marshalCanonical(full)
	if err != nil {
		return fmt.Errorf("encode full contract: %w", err)
	}

	console, err := cloneDocument(full)
	if err != nil {
		return err
	}
	if err := filterConsoleOperations(console, policies); err != nil {
		return err
	}
	console["x-aisphere-contract"] = map[string]any{
		"audience": "iam-console",
		"source":   "protobuf",
		"exposures": []string{
			"PUBLIC",
			"AUTHENTICATED",
			"AUTHORIZED",
		},
	}
	consoleBytes, err := marshalCanonical(console)
	if err != nil {
		return fmt.Errorf("encode console contract: %w", err)
	}

	lock := contractLock{
		Version:   1,
		Source:    "api/**/*.proto",
		Generator: "protoc-gen-openapiv2@v2.29.0 + cmd/openapi-contract",
		Full: contractHash{
			File:   filepath.ToSlash(fullOutput),
			SHA256: digest(fullBytes),
		},
		Console: contractHash{
			File:   filepath.ToSlash(consoleOutput),
			SHA256: digest(consoleBytes),
		},
	}
	lockBytes, err := json.MarshalIndent(lock, "", "  ")
	if err != nil {
		return fmt.Errorf("encode contract lock: %w", err)
	}
	lockBytes = append(lockBytes, '\n')

	outputs := map[string][]byte{
		fullOutput:    fullBytes,
		consoleOutput: consoleBytes,
		lockOutput:    lockBytes,
	}
	for path, content := range outputs {
		if check {
			if err := compareFile(path, content); err != nil {
				return err
			}
			continue
		}
		if err := writeFile(path, content); err != nil {
			return err
		}
	}
	return nil
}

func collectRoutePolicies(root string) (map[routeKey]routePolicy, error) {
	policies := make(map[routeKey]routePolicy)
	err := filepath.WalkDir(root, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || filepath.Ext(path) != ".proto" {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return collectFilePolicies(path, string(content), policies)
	})
	if err != nil {
		return nil, fmt.Errorf("scan proto contracts: %w", err)
	}
	if len(policies) == 0 {
		return nil, fmt.Errorf("no HTTP route policies found under %q", root)
	}
	return policies, nil
}

func collectFilePolicies(filename, content string, policies map[routeKey]routePolicy) error {
	for _, serviceMatch := range servicePattern.FindAllStringSubmatchIndex(content, -1) {
		serviceName := content[serviceMatch[2]:serviceMatch[3]]
		serviceOpen := serviceMatch[1] - 1
		serviceClose, err := matchingBrace(content, serviceOpen)
		if err != nil {
			return fmt.Errorf("%s: service %s: %w", filename, serviceName, err)
		}
		serviceBody := content[serviceOpen+1 : serviceClose]
		for _, rpcMatch := range rpcPattern.FindAllStringSubmatchIndex(serviceBody, -1) {
			rpcName := serviceBody[rpcMatch[2]:rpcMatch[3]]
			rpcOpen := rpcMatch[1] - 1
			rpcClose, err := matchingBrace(serviceBody, rpcOpen)
			if err != nil {
				return fmt.Errorf("%s: %s.%s: %w", filename, serviceName, rpcName, err)
			}
			rpcBody := serviceBody[rpcOpen+1 : rpcClose]
			httpMatches := httpPattern.FindAllStringSubmatch(rpcBody, -1)
			if len(httpMatches) == 0 {
				continue
			}
			exposureMatch := exposurePattern.FindStringSubmatch(rpcBody)
			if len(exposureMatch) != 2 {
				return fmt.Errorf("%s: %s.%s has google.api.http but no access exposure", filename, serviceName, rpcName)
			}
			policy := routePolicy{Exposure: exposureMatch[1], Service: serviceName, RPC: rpcName}
			for _, match := range httpMatches {
				key := routeKey{Method: strings.ToLower(match[1]), Path: normalizePath(match[2])}
				if previous, exists := policies[key]; exists && previous != policy {
					return fmt.Errorf("%s: route %s %s conflicts between %s.%s and %s.%s", filename, strings.ToUpper(key.Method), match[2], previous.Service, previous.RPC, policy.Service, policy.RPC)
				}
				policies[key] = policy
			}
		}
	}
	return nil
}

func matchingBrace(content string, open int) (int, error) {
	if open < 0 || open >= len(content) || content[open] != '{' {
		return 0, errors.New("invalid opening brace")
	}
	depth := 0
	inString := false
	escaped := false
	for i := open; i < len(content); i++ {
		ch := content[i]
		if inString {
			if escaped {
				escaped = false
				continue
			}
			if ch == '\\' {
				escaped = true
				continue
			}
			if ch == '"' {
				inString = false
			}
			continue
		}
		if ch == '"' {
			inString = true
			continue
		}
		switch ch {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return i, nil
			}
		}
	}
	return 0, errors.New("unclosed block")
}

func filterConsoleOperations(document map[string]any, policies map[routeKey]routePolicy) error {
	paths, ok := document["paths"].(map[string]any)
	if !ok {
		return errors.New("OpenAPI paths is not an object")
	}

	allowedMethods := map[string]struct{}{
		"get": {}, "post": {}, "put": {}, "patch": {}, "delete": {},
	}
	pathNames := make([]string, 0, len(paths))
	for path := range paths {
		pathNames = append(pathNames, path)
	}
	sort.Strings(pathNames)

	for _, path := range pathNames {
		item, ok := paths[path].(map[string]any)
		if !ok {
			return fmt.Errorf("OpenAPI path %q is not an object", path)
		}
		kept := 0
		for method := range allowedMethods {
			operation, exists := item[method]
			if !exists {
				continue
			}
			policy, declared := policies[routeKey{Method: method, Path: normalizePath(path)}]
			if !declared || !isConsoleExposure(policy.Exposure) {
				delete(item, method)
				continue
			}
			operationObject, ok := operation.(map[string]any)
			if !ok {
				return fmt.Errorf("OpenAPI operation %s %s is not an object", strings.ToUpper(method), path)
			}
			operationObject["x-aisphere-exposure"] = policy.Exposure
			operationObject["x-aisphere-rpc"] = policy.Service + "." + policy.RPC
			kept++
		}
		if kept == 0 {
			delete(paths, path)
		}
	}
	return nil
}

func isConsoleExposure(exposure string) bool {
	switch strings.ToUpper(strings.TrimSpace(exposure)) {
	case "PUBLIC", "AUTHENTICATED", "AUTHORIZED":
		return true
	default:
		return false
	}
}

func normalizePath(path string) string {
	return pathVariable.ReplaceAllString(path, "{}")
}

func cloneDocument(input map[string]any) (map[string]any, error) {
	encoded, err := json.Marshal(input)
	if err != nil {
		return nil, fmt.Errorf("clone OpenAPI document: %w", err)
	}
	var output map[string]any
	if err := json.Unmarshal(encoded, &output); err != nil {
		return nil, fmt.Errorf("clone OpenAPI document: %w", err)
	}
	return output, nil
}

func marshalCanonical(value any) ([]byte, error) {
	encoded, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(encoded, '\n'), nil
}

func digest(content []byte) string {
	sum := sha256.Sum256(content)
	return hex.EncodeToString(sum[:])
}

func compareFile(path string, expected []byte) error {
	actual, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("contract output %q is missing or unreadable: %w", path, err)
	}
	if !bytes.Equal(actual, expected) {
		return fmt.Errorf("contract output %q is stale; run make openapi", path)
	}
	return nil
}

func writeFile(path string, content []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create output directory for %q: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write contract output %q: %w", path, err)
	}
	return nil
}
