// Code generated by protoc-gen-go-authz. DO NOT EDIT.
// versions:
// - protoc-gen-go-authz v0.4.1
// source: iam/resource/v1/resource.proto

package resourcev1

import (
	context "context"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	contextx "github.com/aisphereio/kernel/contextx"
	requestx "github.com/aisphereio/kernel/requestx"
	grpc "google.golang.org/grpc"
	strings "strings"
)

var _ = grpc.EmptyCallOption{}

var ResourceServiceAuthzRules = authz.Rules{
	"/iam.resource.v1.ResourceService/RegisterResourceType": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "RegisterResourceType",
		FullMethod: "/iam.resource.v1.ResourceService/RegisterResourceType",
		Action:     "manage",
		Resource:   "iam:resource_type",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource_type.register",
		AuditRisk:  "high",
	},
	"/iam.resource.v1.ResourceService/GetResourceType": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "GetResourceType",
		FullMethod: "/iam.resource.v1.ResourceService/GetResourceType",
		Action:     "read",
		Resource:   "iam:resource_type:{type}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource_type.get",
		AuditRisk:  "low",
	},
	"/iam.resource.v1.ResourceService/ListResourceTypes": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "ListResourceTypes",
		FullMethod: "/iam.resource.v1.ResourceService/ListResourceTypes",
		Action:     "list",
		Resource:   "iam:resource_type:*",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource_type.list",
		AuditRisk:  "medium",
	},
	"/iam.resource.v1.ResourceService/GetResource": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "GetResource",
		FullMethod: "/iam.resource.v1.ResourceService/GetResource",
		Action:     "read",
		Resource:   "iam:resource",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource.get",
		AuditRisk:  "low",
	},
	"/iam.resource.v1.ResourceService/ListResources": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "ListResources",
		FullMethod: "/iam.resource.v1.ResourceService/ListResources",
		Action:     "list",
		Resource:   "iam:resource",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource.list",
		AuditRisk:  "medium",
	},
	"/iam.resource.v1.ResourceService/ListResourceBindings": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "ListResourceBindings",
		FullMethod: "/iam.resource.v1.ResourceService/ListResourceBindings",
		Action:     "list",
		Resource:   "iam:resource_binding",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource_binding.list",
		AuditRisk:  "medium",
	},
	"/iam.resource.v1.ResourceService/ListExternalResourceBindings": {
		Service:    "iam.resource.v1.ResourceService",
		Method:     "ListExternalResourceBindings",
		FullMethod: "/iam.resource.v1.ResourceService/ListExternalResourceBindings",
		Action:     "list",
		Resource:   "iam:external_resource_binding",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.external_resource_binding.list",
		AuditRisk:  "medium",
	},
}

const ResourceServiceAuthzManifestJSON = `{
  "methods": [
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "RegisterResourceType",
      "full_method": "/iam.resource.v1.ResourceService/RegisterResourceType",
      "action": "manage",
      "resource": "iam:resource_type",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource_type.register",
      "audit_risk": "high"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "GetResourceType",
      "full_method": "/iam.resource.v1.ResourceService/GetResourceType",
      "action": "read",
      "resource": "iam:resource_type:{type}",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource_type.get",
      "audit_risk": "low"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "ListResourceTypes",
      "full_method": "/iam.resource.v1.ResourceService/ListResourceTypes",
      "action": "list",
      "resource": "iam:resource_type:*",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource_type.list",
      "audit_risk": "medium"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "GetResource",
      "full_method": "/iam.resource.v1.ResourceService/GetResource",
      "action": "read",
      "resource": "iam:resource",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource.get",
      "audit_risk": "low"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "ListResources",
      "full_method": "/iam.resource.v1.ResourceService/ListResources",
      "action": "list",
      "resource": "iam:resource",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource.list",
      "audit_risk": "medium"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "ListResourceBindings",
      "full_method": "/iam.resource.v1.ResourceService/ListResourceBindings",
      "action": "list",
      "resource": "iam:resource_binding",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.resource_binding.list",
      "audit_risk": "medium"
    },
    {
      "service": "iam.resource.v1.ResourceService",
      "method": "ListExternalResourceBindings",
      "full_method": "/iam.resource.v1.ResourceService/ListExternalResourceBindings",
      "action": "list",
      "resource": "iam:external_resource_binding",
      "audience": "iam-service",
      "mode": "CHECK_ONLY",
      "audit_event": "iam.external_resource_binding.list",
      "audit_risk": "medium"
    }
  ],
  "service": "iam.resource.v1.ResourceService"
}`

// ResourceServiceRequestInfoResolver maps generated proto access policy into requestx.Info.
// It should be passed to autowire.WithRequestInfoResolver / WithClientRequestInfoResolver.
func ResourceServiceRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	rule, ok := ResourceServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = ResourceServiceAuthzRules[_ResourceServiceNormalizeOperation(operation)]
	}
	if !ok {
		return requestx.Info{}, false, nil
	}
	info := requestx.Info{
		Service:       rule.Service,
		Method:        rule.Method,
		Operation:     rule.FullMethod,
		Exposure:      v1.Exposure_AUTHORIZED,
		Action:        rule.Action,
		Resource:      rule.Resource,
		TargetService: rule.Audience,
		Labels:        map[string]string{"authz_mode": string(rule.Mode)},
	}
	if rule.AuditEvent != "" {
		info.Labels["audit_event"] = rule.AuditEvent
	}
	if rule.AuditRisk != "" {
		info.Labels["audit_risk"] = rule.AuditRisk
	}
	if rule.Capability != "" {
		info.Labels["capability"] = rule.Capability
	}
	return info.Normalize(), true, nil
}

// ResourceServiceAccessResolver maps generated proto authz rules into accessx.Check.
// It matches middleware/access.Resolver, so services can pass it directly to autowire.WithAccess.
func ResourceServiceAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := ResourceServiceAuthzRules[operation]
	if !ok && operation != "" {
		rule, ok = ResourceServiceAuthzRules[_ResourceServiceNormalizeOperation(operation)]
	}
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _ResourceServiceNormalizeOperation(operation string) string {
	switch operation {
	case "RegisterResourceType", "iam.resource.v1.ResourceService/RegisterResourceType":
		return "/iam.resource.v1.ResourceService/RegisterResourceType"
	case "GetResourceType", "iam.resource.v1.ResourceService/GetResourceType":
		return "/iam.resource.v1.ResourceService/GetResourceType"
	case "ListResourceTypes", "iam.resource.v1.ResourceService/ListResourceTypes":
		return "/iam.resource.v1.ResourceService/ListResourceTypes"
	case "GetResource", "iam.resource.v1.ResourceService/GetResource":
		return "/iam.resource.v1.ResourceService/GetResource"
	case "ListResources", "iam.resource.v1.ResourceService/ListResources":
		return "/iam.resource.v1.ResourceService/ListResources"
	case "ListResourceBindings", "iam.resource.v1.ResourceService/ListResourceBindings":
		return "/iam.resource.v1.ResourceService/ListResourceBindings"
	case "ListExternalResourceBindings", "iam.resource.v1.ResourceService/ListExternalResourceBindings":
		return "/iam.resource.v1.ResourceService/ListExternalResourceBindings"
	default:
		return operation
	}
}

type ResourceServiceSecureClient struct {
	raw      ResourceServiceClient
	guard    authz.Guard
	resolver authz.RuleResolver
}

func NewResourceServiceSecureClient(raw ResourceServiceClient, guard authz.Guard) *ResourceServiceSecureClient {
	return &ResourceServiceSecureClient{raw: raw, guard: guard, resolver: authz.RuleResolver{}}
}

var _ ResourceServiceClient = (*ResourceServiceSecureClient)(nil)

func (c *ResourceServiceSecureClient) RegisterResourceType(ctx context.Context, in *RegisterResourceTypeRequest, opts ...grpc.CallOption) (*ResourceType, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/RegisterResourceType"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.RegisterResourceType(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) GetResourceType(ctx context.Context, in *GetResourceTypeRequest, opts ...grpc.CallOption) (*ResourceType, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/GetResourceType"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.GetResourceType(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) ListResourceTypes(ctx context.Context, in *ListResourceTypesRequest, opts ...grpc.CallOption) (*ListResourceTypesReply, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/ListResourceTypes"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ListResourceTypes(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) UpsertResource(ctx context.Context, in *UpsertResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	return c.raw.UpsertResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/GetResource"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.GetResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesReply, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/ListResources"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ListResources(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) MoveResource(ctx context.Context, in *MoveResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	return c.raw.MoveResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) ArchiveResource(ctx context.Context, in *ArchiveResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	return c.raw.ArchiveResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceReply, error) {
	return c.raw.DeleteResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) BindResource(ctx context.Context, in *BindResourceRequest, opts ...grpc.CallOption) (*ResourceBinding, error) {
	return c.raw.BindResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) UnbindResource(ctx context.Context, in *UnbindResourceRequest, opts ...grpc.CallOption) (*UnbindResourceReply, error) {
	return c.raw.UnbindResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) ListResourceBindings(ctx context.Context, in *ListResourceBindingsRequest, opts ...grpc.CallOption) (*ListResourceBindingsReply, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/ListResourceBindings"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ListResourceBindings(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) BindExternalResource(ctx context.Context, in *BindExternalResourceRequest, opts ...grpc.CallOption) (*ExternalResourceBinding, error) {
	return c.raw.BindExternalResource(ctx, in, opts...)
}

func (c *ResourceServiceSecureClient) ListExternalResourceBindings(ctx context.Context, in *ListExternalResourceBindingsRequest, opts ...grpc.CallOption) (*ListExternalResourceBindingsReply, error) {
	if c != nil && c.guard != nil {
		rule := ResourceServiceAuthzRules["/iam.resource.v1.ResourceService/ListExternalResourceBindings"]
		resource, err := c.resolver.ResolveResource(rule, in)
		if err != nil {
			return nil, err
		}
		subject := _ResourceServiceAuthzSubjectFromContext(ctx)
		switch rule.Mode {
		case authz.RuleModeScopedToken:
			token, decision, err := c.guard.RequireScopedToken(ctx, authz.ScopedTokenRequest{Subject: subject, Action: rule.Action, Resource: resource, Audience: rule.Audience, Rule: rule, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
			if token != "" {
				ctx = contextx.WithScopedToken(ctx, token)
			}
		case authz.RuleModeCheckOnly:
			decision, err := c.guard.Require(ctx, authz.CheckRequest{Subject: subject, Resource: resource, Permission: rule.Action, TenantID: contextx.TenantFromContext(ctx)})
			if err != nil {
				return nil, err
			}
			if decision.ConsistencyToken != "" {
				ctx = contextx.WithAuthzDecisionID(ctx, decision.ConsistencyToken)
			}
		case authz.RuleModeSelfCheck:
		// SELF_CHECK means the target resource service performs the final check.
		case authz.RuleModeUnspecified:
			return nil, authz.ErrInvalidRequest("authz rule mode must not be UNSPECIFIED")
		default:
			return nil, authz.ErrInvalidRequest("unsupported authz rule mode: " + string(rule.Mode))
		}
	}
	return c.raw.ListExternalResourceBindings(ctx, in, opts...)
}

func _ResourceServiceAuthzSubjectFromContext(ctx context.Context) authz.SubjectRef {
	p := contextx.PrincipalFromContext(ctx)
	if p == nil {
		return authz.SubjectRef{}
	}
	typ := authz.SubjectTypeUser
	if strings.HasPrefix(p.SubjectID, "svc:") {
		typ = authz.SubjectTypeService
	}
	return authz.SubjectRef{Type: typ, ID: p.SubjectID}
}
