// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: iam/resource/v1/resource.proto

package resourcev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRef) Reset() {
	*x = ResourceRef{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRef) ProtoMessage() {}

func (x *ResourceRef) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRef.ProtoReflect.Descriptor instead.
func (*ResourceRef) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectRef) Reset() {
	*x = SubjectRef{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectRef) ProtoMessage() {}

func (x *SubjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectRef.ProtoReflect.Descriptor instead.
func (*SubjectRef) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{1}
}

func (x *SubjectRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubjectRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubjectRef) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type ResourceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,2,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	OwnerService  string                 `protobuf:"bytes,3,opt,name=owner_service,json=ownerService,proto3" json:"owner_service,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ParentTypes   []string               `protobuf:"bytes,6,rep,name=parent_types,json=parentTypes,proto3" json:"parent_types,omitempty"`
	Grantable     bool                   `protobuf:"varint,7,opt,name=grantable,proto3" json:"grantable,omitempty"`
	Auditable     bool                   `protobuf:"varint,8,opt,name=auditable,proto3" json:"auditable,omitempty"`
	SpicedbType   string                 `protobuf:"bytes,9,opt,name=spicedb_type,json=spicedbType,proto3" json:"spicedb_type,omitempty"`
	Relations     []string               `protobuf:"bytes,10,rep,name=relations,proto3" json:"relations,omitempty"`
	Permissions   []string               `protobuf:"bytes,11,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      *structpb.Struct       `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Status        string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceType) Reset() {
	*x = ResourceType{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceType) ProtoMessage() {}

func (x *ResourceType) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceType.ProtoReflect.Descriptor instead.
func (*ResourceType) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceType) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ResourceType) GetOwnerService() string {
	if x != nil {
		return x.OwnerService
	}
	return ""
}

func (x *ResourceType) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResourceType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ResourceType) GetParentTypes() []string {
	if x != nil {
		return x.ParentTypes
	}
	return nil
}

func (x *ResourceType) GetGrantable() bool {
	if x != nil {
		return x.Grantable
	}
	return false
}

func (x *ResourceType) GetAuditable() bool {
	if x != nil {
		return x.Auditable
	}
	return false
}

func (x *ResourceType) GetSpicedbType() string {
	if x != nil {
		return x.SpicedbType
	}
	return ""
}

func (x *ResourceType) GetRelations() []string {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *ResourceType) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *ResourceType) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ResourceType) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResourceType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResourceType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Resource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ref             *ResourceRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	OrgId           string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId       string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Parent          *ResourceRef           `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	OwnerService    string                 `protobuf:"bytes,5,opt,name=owner_service,json=ownerService,proto3" json:"owner_service,omitempty"`
	OwnerResourceId string                 `protobuf:"bytes,6,opt,name=owner_resource_id,json=ownerResourceId,proto3" json:"owner_resource_id,omitempty"`
	Slug            string                 `protobuf:"bytes,7,opt,name=slug,proto3" json:"slug,omitempty"`
	DisplayName     string                 `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Path            string                 `protobuf:"bytes,9,opt,name=path,proto3" json:"path,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Visibility      string                 `protobuf:"bytes,11,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Grantable       bool                   `protobuf:"varint,12,opt,name=grantable,proto3" json:"grantable,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations     map[string]string      `protobuf:"bytes,14,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata        *structpb.Struct       `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedBy       *SubjectRef            `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{3}
}

func (x *Resource) GetRef() *ResourceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Resource) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Resource) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Resource) GetParent() *ResourceRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Resource) GetOwnerService() string {
	if x != nil {
		return x.OwnerService
	}
	return ""
}

func (x *Resource) GetOwnerResourceId() string {
	if x != nil {
		return x.OwnerResourceId
	}
	return ""
}

func (x *Resource) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Resource) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Resource) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Resource) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Resource) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Resource) GetGrantable() bool {
	if x != nil {
		return x.Grantable
	}
	return false
}

func (x *Resource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Resource) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Resource) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetCreatedBy() *SubjectRef {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *Resource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Resource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Resource) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ResourceBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        *ResourceRef           `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Target        *ResourceRef           `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedBy     *SubjectRef            `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceBinding) Reset() {
	*x = ResourceBinding{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceBinding) ProtoMessage() {}

func (x *ResourceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceBinding.ProtoReflect.Descriptor instead.
func (*ResourceBinding) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceBinding) GetSource() *ResourceRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ResourceBinding) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ResourceBinding) GetTarget() *ResourceRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ResourceBinding) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResourceBinding) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceBinding) GetCreatedBy() *SubjectRef {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *ResourceBinding) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResourceBinding) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExternalResourceBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource      *ResourceRef           `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalType  string                 `protobuf:"bytes,4,opt,name=external_type,json=externalType,proto3" json:"external_type,omitempty"`
	ExternalId    string                 `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ExternalPath  string                 `protobuf:"bytes,6,opt,name=external_path,json=externalPath,proto3" json:"external_path,omitempty"`
	ExternalUrl   string                 `protobuf:"bytes,7,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	SyncMode      string                 `protobuf:"bytes,8,opt,name=sync_mode,json=syncMode,proto3" json:"sync_mode,omitempty"`
	SyncStatus    string                 `protobuf:"bytes,9,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	LastSyncedAt  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_synced_at,json=lastSyncedAt,proto3" json:"last_synced_at,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalResourceBinding) Reset() {
	*x = ExternalResourceBinding{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalResourceBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalResourceBinding) ProtoMessage() {}

func (x *ExternalResourceBinding) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalResourceBinding.ProtoReflect.Descriptor instead.
func (*ExternalResourceBinding) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ExternalResourceBinding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExternalResourceBinding) GetResource() *ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ExternalResourceBinding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExternalResourceBinding) GetExternalType() string {
	if x != nil {
		return x.ExternalType
	}
	return ""
}

func (x *ExternalResourceBinding) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalResourceBinding) GetExternalPath() string {
	if x != nil {
		return x.ExternalPath
	}
	return ""
}

func (x *ExternalResourceBinding) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *ExternalResourceBinding) GetSyncMode() string {
	if x != nil {
		return x.SyncMode
	}
	return ""
}

func (x *ExternalResourceBinding) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *ExternalResourceBinding) GetLastSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSyncedAt
	}
	return nil
}

func (x *ExternalResourceBinding) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResourceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  *ResourceType          `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResourceTypeRequest) Reset() {
	*x = RegisterResourceTypeRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResourceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResourceTypeRequest) ProtoMessage() {}

func (x *RegisterResourceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResourceTypeRequest.ProtoReflect.Descriptor instead.
func (*RegisterResourceTypeRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResourceTypeRequest) GetResourceType() *ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return nil
}

type GetResourceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceTypeRequest) Reset() {
	*x = GetResourceTypeRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceTypeRequest) ProtoMessage() {}

func (x *GetResourceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceTypeRequest.ProtoReflect.Descriptor instead.
func (*GetResourceTypeRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{7}
}

func (x *GetResourceTypeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListResourceTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapabilityId  string                 `protobuf:"bytes,1,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	OwnerService  string                 `protobuf:"bytes,2,opt,name=owner_service,json=ownerService,proto3" json:"owner_service,omitempty"`
	Grantable     *bool                  `protobuf:"varint,3,opt,name=grantable,proto3,oneof" json:"grantable,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTypesRequest) Reset() {
	*x = ListResourceTypesRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTypesRequest) ProtoMessage() {}

func (x *ListResourceTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTypesRequest.ProtoReflect.Descriptor instead.
func (*ListResourceTypesRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{8}
}

func (x *ListResourceTypesRequest) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ListResourceTypesRequest) GetOwnerService() string {
	if x != nil {
		return x.OwnerService
	}
	return ""
}

func (x *ListResourceTypesRequest) GetGrantable() bool {
	if x != nil && x.Grantable != nil {
		return *x.Grantable
	}
	return false
}

func (x *ListResourceTypesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListResourceTypesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceTypes []*ResourceType        `protobuf:"bytes,1,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTypesReply) Reset() {
	*x = ListResourceTypesReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTypesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTypesReply) ProtoMessage() {}

func (x *ListResourceTypesReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTypesReply.ProtoReflect.Descriptor instead.
func (*ListResourceTypesReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{9}
}

func (x *ListResourceTypesReply) GetResourceTypes() []*ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

type UpsertResourceRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Resource                *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	WriteParentRelationship bool                   `protobuf:"varint,2,opt,name=write_parent_relationship,json=writeParentRelationship,proto3" json:"write_parent_relationship,omitempty"`
	CreateDefaultOwnerGrant bool                   `protobuf:"varint,3,opt,name=create_default_owner_grant,json=createDefaultOwnerGrant,proto3" json:"create_default_owner_grant,omitempty"`
	Owner                   *SubjectRef            `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpsertResourceRequest) Reset() {
	*x = UpsertResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResourceRequest) ProtoMessage() {}

func (x *UpsertResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResourceRequest.ProtoReflect.Descriptor instead.
func (*UpsertResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertResourceRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UpsertResourceRequest) GetWriteParentRelationship() bool {
	if x != nil {
		return x.WriteParentRelationship
	}
	return false
}

func (x *UpsertResourceRequest) GetCreateDefaultOwnerGrant() bool {
	if x != nil {
		return x.CreateDefaultOwnerGrant
	}
	return false
}

func (x *UpsertResourceRequest) GetOwner() *SubjectRef {
	if x != nil {
		return x.Owner
	}
	return nil
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{11}
}

func (x *GetResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *GetResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Parent        *ResourceRef           `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	OwnerService  string                 `protobuf:"bytes,5,opt,name=owner_service,json=ownerService,proto3" json:"owner_service,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Visibility    string                 `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PageSize      int32                  `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,10,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{12}
}

func (x *ListResourcesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListResourcesRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListResourcesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListResourcesRequest) GetParent() *ResourceRef {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ListResourcesRequest) GetOwnerService() string {
	if x != nil {
		return x.OwnerService
	}
	return ""
}

func (x *ListResourcesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListResourcesRequest) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *ListResourcesRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourcesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResourcesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesReply) Reset() {
	*x = ListResourcesReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesReply) ProtoMessage() {}

func (x *ListResourcesReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesReply.ProtoReflect.Descriptor instead.
func (*ListResourcesReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{13}
}

func (x *ListResourcesReply) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListResourcesReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListResourcesReply) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type MoveResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	NewParent     *ResourceRef           `protobuf:"bytes,3,opt,name=new_parent,json=newParent,proto3" json:"new_parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResourceRequest) Reset() {
	*x = MoveResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResourceRequest) ProtoMessage() {}

func (x *MoveResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResourceRequest.ProtoReflect.Descriptor instead.
func (*MoveResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{14}
}

func (x *MoveResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *MoveResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *MoveResourceRequest) GetNewParent() *ResourceRef {
	if x != nil {
		return x.NewParent
	}
	return nil
}

type ArchiveResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveResourceRequest) Reset() {
	*x = ArchiveResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveResourceRequest) ProtoMessage() {}

func (x *ArchiveResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveResourceRequest.ProtoReflect.Descriptor instead.
func (*ArchiveResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{15}
}

func (x *ArchiveResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *ArchiveResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ArchiveResourceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceType  string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,3,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResourceRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *DeleteResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DeleteResourceRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

func (x *DeleteResourceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ResourceRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceReply) Reset() {
	*x = DeleteResourceReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceReply) ProtoMessage() {}

func (x *DeleteResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceReply.ProtoReflect.Descriptor instead.
func (*DeleteResourceReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteResourceReply) GetRef() *ResourceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *DeleteResourceReply) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type BindResourceRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Binding                *ResourceBinding       `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	WriteGraphRelationship bool                   `protobuf:"varint,2,opt,name=write_graph_relationship,json=writeGraphRelationship,proto3" json:"write_graph_relationship,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BindResourceRequest) Reset() {
	*x = BindResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindResourceRequest) ProtoMessage() {}

func (x *BindResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindResourceRequest.ProtoReflect.Descriptor instead.
func (*BindResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{18}
}

func (x *BindResourceRequest) GetBinding() *ResourceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *BindResourceRequest) GetWriteGraphRelationship() bool {
	if x != nil {
		return x.WriteGraphRelationship
	}
	return false
}

type UnbindResourceRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BindingId               string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	DeleteGraphRelationship bool                   `protobuf:"varint,2,opt,name=delete_graph_relationship,json=deleteGraphRelationship,proto3" json:"delete_graph_relationship,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UnbindResourceRequest) Reset() {
	*x = UnbindResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResourceRequest) ProtoMessage() {}

func (x *UnbindResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResourceRequest.ProtoReflect.Descriptor instead.
func (*UnbindResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{19}
}

func (x *UnbindResourceRequest) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *UnbindResourceRequest) GetDeleteGraphRelationship() bool {
	if x != nil {
		return x.DeleteGraphRelationship
	}
	return false
}

type UnbindResourceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindingId     string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	Unbound       bool                   `protobuf:"varint,2,opt,name=unbound,proto3" json:"unbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbindResourceReply) Reset() {
	*x = UnbindResourceReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbindResourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbindResourceReply) ProtoMessage() {}

func (x *UnbindResourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbindResourceReply.ProtoReflect.Descriptor instead.
func (*UnbindResourceReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{20}
}

func (x *UnbindResourceReply) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *UnbindResourceReply) GetUnbound() bool {
	if x != nil {
		return x.Unbound
	}
	return false
}

type ListResourceBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *ResourceRef           `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target        *ResourceRef           `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceBindingsRequest) Reset() {
	*x = ListResourceBindingsRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceBindingsRequest) ProtoMessage() {}

func (x *ListResourceBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListResourceBindingsRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{21}
}

func (x *ListResourceBindingsRequest) GetSource() *ResourceRef {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ListResourceBindingsRequest) GetTarget() *ResourceRef {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ListResourceBindingsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListResourceBindingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListResourceBindingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListResourceBindingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListResourceBindingsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*ResourceBinding     `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceBindingsReply) Reset() {
	*x = ListResourceBindingsReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceBindingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceBindingsReply) ProtoMessage() {}

func (x *ListResourceBindingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceBindingsReply.ProtoReflect.Descriptor instead.
func (*ListResourceBindingsReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{22}
}

func (x *ListResourceBindingsReply) GetBindings() []*ResourceBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *ListResourceBindingsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListResourceBindingsReply) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

type BindExternalResourceRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Binding       *ExternalResourceBinding `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindExternalResourceRequest) Reset() {
	*x = BindExternalResourceRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindExternalResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindExternalResourceRequest) ProtoMessage() {}

func (x *BindExternalResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindExternalResourceRequest.ProtoReflect.Descriptor instead.
func (*BindExternalResourceRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{23}
}

func (x *BindExternalResourceRequest) GetBinding() *ExternalResourceBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type ListExternalResourceBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceRef           `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalType  string                 `protobuf:"bytes,3,opt,name=external_type,json=externalType,proto3" json:"external_type,omitempty"`
	ExternalId    string                 `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	SyncStatus    string                 `protobuf:"bytes,5,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalResourceBindingsRequest) Reset() {
	*x = ListExternalResourceBindingsRequest{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalResourceBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalResourceBindingsRequest) ProtoMessage() {}

func (x *ListExternalResourceBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalResourceBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListExternalResourceBindingsRequest) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{24}
}

func (x *ListExternalResourceBindingsRequest) GetResource() *ResourceRef {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ListExternalResourceBindingsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListExternalResourceBindingsRequest) GetExternalType() string {
	if x != nil {
		return x.ExternalType
	}
	return ""
}

func (x *ListExternalResourceBindingsRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ListExternalResourceBindingsRequest) GetSyncStatus() string {
	if x != nil {
		return x.SyncStatus
	}
	return ""
}

func (x *ListExternalResourceBindingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListExternalResourceBindingsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListExternalResourceBindingsReply struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Bindings      []*ExternalResourceBinding `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	NextPageToken string                     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalSize     int64                      `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExternalResourceBindingsReply) Reset() {
	*x = ListExternalResourceBindingsReply{}
	mi := &file_iam_resource_v1_resource_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExternalResourceBindingsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExternalResourceBindingsReply) ProtoMessage() {}

func (x *ListExternalResourceBindingsReply) ProtoReflect() protoreflect.Message {
	mi := &file_iam_resource_v1_resource_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExternalResourceBindingsReply.ProtoReflect.Descriptor instead.
func (*ListExternalResourceBindingsReply) Descriptor() ([]byte, []int) {
	return file_iam_resource_v1_resource_proto_rawDescGZIP(), []int{25}
}

func (x *ListExternalResourceBindingsReply) GetBindings() []*ExternalResourceBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

func (x *ListExternalResourceBindingsReply) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListExternalResourceBindingsReply) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_iam_resource_v1_resource_proto protoreflect.FileDescriptor

const file_iam_resource_v1_resource_proto_rawDesc = "" +
	"\n" +
	"\x1eiam/resource/v1/resource.proto\x12\x0fiam.resource.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"I\n" +
	"\vResourceRef\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x04type\x12\x1a\n" +
	"\x02id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\"d\n" +
	"\n" +
	"SubjectRef\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x04type\x12\x1a\n" +
	"\x02id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\"\xb4\x05\n" +
	"\fResourceType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rcapability_id\x18\x02 \x01(\tR\fcapabilityId\x12#\n" +
	"\rowner_service\x18\x03 \x01(\tR\fownerService\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12!\n" +
	"\fparent_types\x18\x06 \x03(\tR\vparentTypes\x12\x1c\n" +
	"\tgrantable\x18\a \x01(\bR\tgrantable\x12\x1c\n" +
	"\tauditable\x18\b \x01(\bR\tauditable\x12!\n" +
	"\fspicedb_type\x18\t \x01(\tR\vspicedbType\x12\x1c\n" +
	"\trelations\x18\n" +
	" \x03(\tR\trelations\x12 \n" +
	"\vpermissions\x18\v \x03(\tR\vpermissions\x12A\n" +
	"\x06labels\x18\f \x03(\v2).iam.resource.v1.ResourceType.LabelsEntryR\x06labels\x123\n" +
	"\bmetadata\x18\r \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\a\n" +
	"\bResource\x12.\n" +
	"\x03ref\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x03ref\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x124\n" +
	"\x06parent\x18\x04 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06parent\x12#\n" +
	"\rowner_service\x18\x05 \x01(\tR\fownerService\x12*\n" +
	"\x11owner_resource_id\x18\x06 \x01(\tR\x0fownerResourceId\x12\x12\n" +
	"\x04slug\x18\a \x01(\tR\x04slug\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04path\x18\t \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\v \x01(\tR\n" +
	"visibility\x12\x1c\n" +
	"\tgrantable\x18\f \x01(\bR\tgrantable\x12=\n" +
	"\x06labels\x18\r \x03(\v2%.iam.resource.v1.Resource.LabelsEntryR\x06labels\x12L\n" +
	"\vannotations\x18\x0e \x03(\v2*.iam.resource.v1.Resource.AnnotationsEntryR\vannotations\x123\n" +
	"\bmetadata\x18\x0f \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12:\n" +
	"\n" +
	"created_by\x18\x10 \x01(\v2\x1b.iam.resource.v1.SubjectRefR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x03\n" +
	"\x0fResourceBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06source\x18\x02 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06source\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x124\n" +
	"\x06target\x18\x04 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06target\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12:\n" +
	"\n" +
	"created_by\x18\a \x01(\v2\x1b.iam.resource.v1.SubjectRefR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x03\n" +
	"\x17ExternalResourceBinding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\bresource\x18\x02 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\bresource\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12#\n" +
	"\rexternal_type\x18\x04 \x01(\tR\fexternalType\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12#\n" +
	"\rexternal_path\x18\x06 \x01(\tR\fexternalPath\x12!\n" +
	"\fexternal_url\x18\a \x01(\tR\vexternalUrl\x12\x1b\n" +
	"\tsync_mode\x18\b \x01(\tR\bsyncMode\x12\x1f\n" +
	"\vsync_status\x18\t \x01(\tR\n" +
	"syncStatus\x12@\n" +
	"\x0elast_synced_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\flastSyncedAt\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\"f\n" +
	"\x1bRegisterResourceTypeRequest\x12G\n" +
	"\rresource_type\x18\x01 \x01(\v2\x1d.iam.resource.v1.ResourceTypeB\x03\xe0A\x02R\fresourceType\"8\n" +
	"\x16GetResourceTypeRequest\x12\x1e\n" +
	"\x04type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\x04type\"\xad\x01\n" +
	"\x18ListResourceTypesRequest\x12#\n" +
	"\rcapability_id\x18\x01 \x01(\tR\fcapabilityId\x12#\n" +
	"\rowner_service\x18\x02 \x01(\tR\fownerService\x12!\n" +
	"\tgrantable\x18\x03 \x01(\bH\x00R\tgrantable\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB\f\n" +
	"\n" +
	"_grantable\"^\n" +
	"\x16ListResourceTypesReply\x12D\n" +
	"\x0eresource_types\x18\x01 \x03(\v2\x1d.iam.resource.v1.ResourceTypeR\rresourceTypes\"\xff\x01\n" +
	"\x15UpsertResourceRequest\x12:\n" +
	"\bresource\x18\x01 \x01(\v2\x19.iam.resource.v1.ResourceB\x03\xe0A\x02R\bresource\x12:\n" +
	"\x19write_parent_relationship\x18\x02 \x01(\bR\x17writeParentRelationship\x12;\n" +
	"\x1acreate_default_owner_grant\x18\x03 \x01(\bR\x17createDefaultOwnerGrant\x121\n" +
	"\x05owner\x18\x04 \x01(\v2\x1b.iam.resource.v1.SubjectRefR\x05owner\"r\n" +
	"\x12GetResourceRequest\x12/\n" +
	"\rresource_type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\fresourceType\x12+\n" +
	"\vresource_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\"\xb5\x03\n" +
	"\x14ListResourcesRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x124\n" +
	"\x06parent\x18\x04 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06parent\x12#\n" +
	"\rowner_service\x18\x05 \x01(\tR\fownerService\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12I\n" +
	"\x06labels\x18\b \x03(\v21.iam.resource.v1.ListResourcesRequest.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tpage_size\x18\t \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\n" +
	" \x01(\tR\tpageToken\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\x12ListResourcesReply\x127\n" +
	"\tresources\x18\x01 \x03(\v2\x19.iam.resource.v1.ResourceR\tresources\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"\xb5\x01\n" +
	"\x13MoveResourceRequest\x12/\n" +
	"\rresource_type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\fresourceType\x12+\n" +
	"\vresource_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\x12@\n" +
	"\n" +
	"new_parent\x18\x03 \x01(\v2\x1c.iam.resource.v1.ResourceRefB\x03\xe0A\x02R\tnewParent\"\x8e\x01\n" +
	"\x16ArchiveResourceRequest\x12/\n" +
	"\rresource_type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\fresourceType\x12+\n" +
	"\vresource_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xae\x01\n" +
	"\x15DeleteResourceRequest\x12/\n" +
	"\rresource_type\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\fresourceType\x12+\n" +
	"\vresource_id\x18\x02 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"resourceId\x12\x1f\n" +
	"\vhard_delete\x18\x03 \x01(\bR\n" +
	"hardDelete\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"_\n" +
	"\x13DeleteResourceReply\x12.\n" +
	"\x03ref\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x03ref\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\x90\x01\n" +
	"\x13BindResourceRequest\x12?\n" +
	"\abinding\x18\x01 \x01(\v2 .iam.resource.v1.ResourceBindingB\x03\xe0A\x02R\abinding\x128\n" +
	"\x18write_graph_relationship\x18\x02 \x01(\bR\x16writeGraphRelationship\"~\n" +
	"\x15UnbindResourceRequest\x12)\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tB\n" +
	"\xe0A\x02\xbaH\x04r\x02\x10\x01R\tbindingId\x12:\n" +
	"\x19delete_graph_relationship\x18\x02 \x01(\bR\x17deleteGraphRelationship\"N\n" +
	"\x13UnbindResourceReply\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12\x18\n" +
	"\aunbound\x18\x02 \x01(\bR\aunbound\"\xf9\x01\n" +
	"\x1bListResourceBindingsRequest\x124\n" +
	"\x06source\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06source\x124\n" +
	"\x06target\x18\x02 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\x06target\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\xa0\x01\n" +
	"\x19ListResourceBindingsReply\x12<\n" +
	"\bbindings\x18\x01 \x03(\v2 .iam.resource.v1.ResourceBindingR\bbindings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\"f\n" +
	"\x1bBindExternalResourceRequest\x12G\n" +
	"\abinding\x18\x01 \x01(\v2(.iam.resource.v1.ExternalResourceBindingB\x03\xe0A\x02R\abinding\"\x9e\x02\n" +
	"#ListExternalResourceBindingsRequest\x128\n" +
	"\bresource\x18\x01 \x01(\v2\x1c.iam.resource.v1.ResourceRefR\bresource\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12#\n" +
	"\rexternal_type\x18\x03 \x01(\tR\fexternalType\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x1f\n" +
	"\vsync_status\x18\x05 \x01(\tR\n" +
	"syncStatus\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\tR\tpageToken\"\xb0\x01\n" +
	"!ListExternalResourceBindingsReply\x12D\n" +
	"\bbindings\x18\x01 \x03(\v2(.iam.resource.v1.ExternalResourceBindingR\bbindings\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize2\xde\x1e\n" +
	"\x0fResourceService\x12\xed\x01\n" +
	"\x14RegisterResourceType\x12,.iam.resource.v1.RegisterResourceTypeRequest\x1a\x1d.iam.resource.v1.ResourceType\"\x87\x01\x92\xf4\x18T\b\x03\x12*\n" +
	"\x06manage\x12\x11iam:resource_type\x1a\viam-service \x01\x1a$\b\x01\x12\x1aiam.resource_type.register\x1a\x04high\x82\xd3\xe4\x93\x02):\x01*\"$/v1/iam/control-plane/resource-types\x12\xe6\x01\n" +
	"\x0fGetResourceType\x12'.iam.resource.v1.GetResourceTypeRequest\x1a\x1d.iam.resource.v1.ResourceType\"\x8a\x01\x92\xf4\x18S\b\x03\x12/\n" +
	"\x04read\x12\x18iam:resource_type:{type}\x1a\viam-service \x01\x1a\x1e\b\x01\x12\x15iam.resource_type.get\x1a\x03low\x82\xd3\xe4\x93\x02-\x12+/v1/iam/control-plane/resource-types/{type}\x12\xec\x01\n" +
	"\x11ListResourceTypes\x12).iam.resource.v1.ListResourceTypesRequest\x1a'.iam.resource.v1.ListResourceTypesReply\"\x82\x01\x92\xf4\x18R\b\x03\x12*\n" +
	"\x04list\x12\x13iam:resource_type:*\x1a\viam-service \x01\x1a\"\b\x01\x12\x16iam.resource_type.list\x1a\x06medium\x82\xd3\xe4\x93\x02&\x12$/v1/iam/control-plane/resource-types\x12\x8a\x02\n" +
	"\x0eUpsertResource\x12&.iam.resource.v1.UpsertResourceRequest\x1a\x19.iam.resource.v1.Resource\"\xb4\x01\x92\xf4\x18\x85\x01\b\x04\x12%\n" +
	"\x06upsert\x12\fiam:resource\x1a\viam-service \x01\x1a\x1d\b\x01\x12\x13iam.resource.upsert\x1a\x04high2;Resource projections are written by trusted owner services.\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/iam/control-plane/resources\x12\xdb\x01\n" +
	"\vGetResource\x12#.iam.resource.v1.GetResourceRequest\x1a\x19.iam.resource.v1.Resource\"\x8b\x01\x92\xf4\x18B\b\x03\x12#\n" +
	"\x04read\x12\fiam:resource\x1a\viam-service \x01\x1a\x19\b\x01\x12\x10iam.resource.get\x1a\x03low\x82\xd3\xe4\x93\x02?\x12=/v1/iam/control-plane/resources/{resource_type}/{resource_id}\x12\xce\x01\n" +
	"\rListResources\x12%.iam.resource.v1.ListResourcesRequest\x1a#.iam.resource.v1.ListResourcesReply\"q\x92\xf4\x18F\b\x03\x12#\n" +
	"\x04list\x12\fiam:resource\x1a\viam-service \x01\x1a\x1d\b\x01\x12\x11iam.resource.list\x1a\x06medium\x82\xd3\xe4\x93\x02!\x12\x1f/v1/iam/control-plane/resources\x12\xaf\x02\n" +
	"\fMoveResource\x12$.iam.resource.v1.MoveResourceRequest\x1a\x19.iam.resource.v1.Resource\"\xdd\x01\x92\xf4\x18\x8b\x01\b\x04\x12#\n" +
	"\x04move\x12\fiam:resource\x1a\viam-service \x01\x1a\x1b\b\x01\x12\x11iam.resource.move\x1a\x04high2EResource moves are requested only by trusted resource owner services.\x82\xd3\xe4\x93\x02G:\x01*\"B/v1/iam/control-plane/resources/{resource_type}/{resource_id}/move\x12\xc0\x02\n" +
	"\x0fArchiveResource\x12'.iam.resource.v1.ArchiveResourceRequest\x1a\x19.iam.resource.v1.Resource\"\xe8\x01\x92\xf4\x18\x93\x01\b\x04\x12&\n" +
	"\aarchive\x12\fiam:resource\x1a\viam-service \x01\x1a\x1e\b\x01\x12\x14iam.resource.archive\x1a\x04high2GResource archival is synchronized from trusted resource owner services.\x82\xd3\xe4\x93\x02J:\x01*\"E/v1/iam/control-plane/resources/{resource_type}/{resource_id}/archive\x12\xbc\x02\n" +
	"\x0eDeleteResource\x12&.iam.resource.v1.DeleteResourceRequest\x1a$.iam.resource.v1.DeleteResourceReply\"\xdb\x01\x92\xf4\x18\x91\x01\b\x04\x12%\n" +
	"\x06delete\x12\fiam:resource\x1a\viam-service \x01\x1a\x1d\b\x01\x12\x13iam.resource.delete\x1a\x04high2GResource deletion is synchronized from trusted resource owner services.\x82\xd3\xe4\x93\x02?*=/v1/iam/control-plane/resources/{resource_type}/{resource_id}\x12\xa3\x02\n" +
	"\fBindResource\x12$.iam.resource.v1.BindResourceRequest\x1a .iam.resource.v1.ResourceBinding\"\xca\x01\x92\xf4\x18\x93\x01\b\x04\x12+\n" +
	"\x04bind\x12\x14iam:resource_binding\x1a\viam-service \x01\x1a#\b\x01\x12\x19iam.resource_binding.bind\x1a\x04high2=Resource bindings are projected by trusted platform services.\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/iam/control-plane/resource-bindings\x12\xd6\x02\n" +
	"\x0eUnbindResource\x12&.iam.resource.v1.UnbindResourceRequest\x1a$.iam.resource.v1.UnbindResourceReply\"\xf5\x01\x92\xf4\x18\xaa\x01\b\x04\x12:\n" +
	"\x06unbind\x12!iam:resource_binding:{binding_id}\x1a\viam-service \x01\x1a%\b\x01\x12\x1biam.resource_binding.unbind\x1a\x04high2CResource binding removal is projected by trusted platform services.\x82\xd3\xe4\x93\x02@:\x01*\";/v1/iam/control-plane/resource-bindings/{binding_id}/unbind\x12\xfc\x01\n" +
	"\x14ListResourceBindings\x12,.iam.resource.v1.ListResourceBindingsRequest\x1a*.iam.resource.v1.ListResourceBindingsReply\"\x89\x01\x92\xf4\x18V\b\x03\x12+\n" +
	"\x04list\x12\x14iam:resource_binding\x1a\viam-service \x01\x1a%\b\x01\x12\x19iam.resource_binding.list\x1a\x06medium\x82\xd3\xe4\x93\x02)\x12'/v1/iam/control-plane/resource-bindings\x12\xe2\x02\n" +
	"\x14BindExternalResource\x12,.iam.resource.v1.BindExternalResourceRequest\x1a(.iam.resource.v1.ExternalResourceBinding\"\xf1\x01\x92\xf4\x18\xb1\x01\b\x04\x124\n" +
	"\x04bind\x12\x1diam:external_resource_binding\x1a\viam-service \x01\x1a,\b\x01\x12\"iam.external_resource_binding.bind\x1a\x04high2IExternal resource mappings are projected by trusted integration services.\x82\xd3\xe4\x93\x025:\x01*\"0/v1/iam/control-plane/external-resource-bindings\x12\xaf\x02\n" +
	"\x1cListExternalResourceBindings\x124.iam.resource.v1.ListExternalResourceBindingsRequest\x1a2.iam.resource.v1.ListExternalResourceBindingsReply\"\xa4\x01\x92\xf4\x18h\b\x03\x124\n" +
	"\x04list\x12\x1diam:external_resource_binding\x1a\viam-service \x01\x1a.\b\x01\x12\"iam.external_resource_binding.list\x1a\x06medium\x82\xd3\xe4\x93\x022\x120/v1/iam/control-plane/external-resource-bindingsBCZAgithub.com/aisphereio/aisphere-iam/api/iam/resource/v1;resourcev1b\x06proto3"

var (
	file_iam_resource_v1_resource_proto_rawDescOnce sync.Once
	file_iam_resource_v1_resource_proto_rawDescData []byte
)

func file_iam_resource_v1_resource_proto_rawDescGZIP() []byte {
	file_iam_resource_v1_resource_proto_rawDescOnce.Do(func() {
		file_iam_resource_v1_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_iam_resource_v1_resource_proto_rawDesc), len(file_iam_resource_v1_resource_proto_rawDesc)))
	})
	return file_iam_resource_v1_resource_proto_rawDescData
}

var file_iam_resource_v1_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_iam_resource_v1_resource_proto_goTypes = []any{
	(*ResourceRef)(nil),                         // 0: iam.resource.v1.ResourceRef
	(*SubjectRef)(nil),                          // 1: iam.resource.v1.SubjectRef
	(*ResourceType)(nil),                        // 2: iam.resource.v1.ResourceType
	(*Resource)(nil),                            // 3: iam.resource.v1.Resource
	(*ResourceBinding)(nil),                     // 4: iam.resource.v1.ResourceBinding
	(*ExternalResourceBinding)(nil),             // 5: iam.resource.v1.ExternalResourceBinding
	(*RegisterResourceTypeRequest)(nil),         // 6: iam.resource.v1.RegisterResourceTypeRequest
	(*GetResourceTypeRequest)(nil),              // 7: iam.resource.v1.GetResourceTypeRequest
	(*ListResourceTypesRequest)(nil),            // 8: iam.resource.v1.ListResourceTypesRequest
	(*ListResourceTypesReply)(nil),              // 9: iam.resource.v1.ListResourceTypesReply
	(*UpsertResourceRequest)(nil),               // 10: iam.resource.v1.UpsertResourceRequest
	(*GetResourceRequest)(nil),                  // 11: iam.resource.v1.GetResourceRequest
	(*ListResourcesRequest)(nil),                // 12: iam.resource.v1.ListResourcesRequest
	(*ListResourcesReply)(nil),                  // 13: iam.resource.v1.ListResourcesReply
	(*MoveResourceRequest)(nil),                 // 14: iam.resource.v1.MoveResourceRequest
	(*ArchiveResourceRequest)(nil),              // 15: iam.resource.v1.ArchiveResourceRequest
	(*DeleteResourceRequest)(nil),               // 16: iam.resource.v1.DeleteResourceRequest
	(*DeleteResourceReply)(nil),                 // 17: iam.resource.v1.DeleteResourceReply
	(*BindResourceRequest)(nil),                 // 18: iam.resource.v1.BindResourceRequest
	(*UnbindResourceRequest)(nil),               // 19: iam.resource.v1.UnbindResourceRequest
	(*UnbindResourceReply)(nil),                 // 20: iam.resource.v1.UnbindResourceReply
	(*ListResourceBindingsRequest)(nil),         // 21: iam.resource.v1.ListResourceBindingsRequest
	(*ListResourceBindingsReply)(nil),           // 22: iam.resource.v1.ListResourceBindingsReply
	(*BindExternalResourceRequest)(nil),         // 23: iam.resource.v1.BindExternalResourceRequest
	(*ListExternalResourceBindingsRequest)(nil), // 24: iam.resource.v1.ListExternalResourceBindingsRequest
	(*ListExternalResourceBindingsReply)(nil),   // 25: iam.resource.v1.ListExternalResourceBindingsReply
	nil,                           // 26: iam.resource.v1.ResourceType.LabelsEntry
	nil,                           // 27: iam.resource.v1.Resource.LabelsEntry
	nil,                           // 28: iam.resource.v1.Resource.AnnotationsEntry
	nil,                           // 29: iam.resource.v1.ListResourcesRequest.LabelsEntry
	(*structpb.Struct)(nil),       // 30: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
}
var file_iam_resource_v1_resource_proto_depIdxs = []int32{
	26, // 0: iam.resource.v1.ResourceType.labels:type_name -> iam.resource.v1.ResourceType.LabelsEntry
	30, // 1: iam.resource.v1.ResourceType.metadata:type_name -> google.protobuf.Struct
	31, // 2: iam.resource.v1.ResourceType.created_at:type_name -> google.protobuf.Timestamp
	31, // 3: iam.resource.v1.ResourceType.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: iam.resource.v1.Resource.ref:type_name -> iam.resource.v1.ResourceRef
	0,  // 5: iam.resource.v1.Resource.parent:type_name -> iam.resource.v1.ResourceRef
	27, // 6: iam.resource.v1.Resource.labels:type_name -> iam.resource.v1.Resource.LabelsEntry
	28, // 7: iam.resource.v1.Resource.annotations:type_name -> iam.resource.v1.Resource.AnnotationsEntry
	30, // 8: iam.resource.v1.Resource.metadata:type_name -> google.protobuf.Struct
	1,  // 9: iam.resource.v1.Resource.created_by:type_name -> iam.resource.v1.SubjectRef
	31, // 10: iam.resource.v1.Resource.created_at:type_name -> google.protobuf.Timestamp
	31, // 11: iam.resource.v1.Resource.updated_at:type_name -> google.protobuf.Timestamp
	31, // 12: iam.resource.v1.Resource.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 13: iam.resource.v1.ResourceBinding.source:type_name -> iam.resource.v1.ResourceRef
	0,  // 14: iam.resource.v1.ResourceBinding.target:type_name -> iam.resource.v1.ResourceRef
	30, // 15: iam.resource.v1.ResourceBinding.metadata:type_name -> google.protobuf.Struct
	1,  // 16: iam.resource.v1.ResourceBinding.created_by:type_name -> iam.resource.v1.SubjectRef
	31, // 17: iam.resource.v1.ResourceBinding.created_at:type_name -> google.protobuf.Timestamp
	31, // 18: iam.resource.v1.ResourceBinding.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 19: iam.resource.v1.ExternalResourceBinding.resource:type_name -> iam.resource.v1.ResourceRef
	31, // 20: iam.resource.v1.ExternalResourceBinding.last_synced_at:type_name -> google.protobuf.Timestamp
	30, // 21: iam.resource.v1.ExternalResourceBinding.metadata:type_name -> google.protobuf.Struct
	2,  // 22: iam.resource.v1.RegisterResourceTypeRequest.resource_type:type_name -> iam.resource.v1.ResourceType
	2,  // 23: iam.resource.v1.ListResourceTypesReply.resource_types:type_name -> iam.resource.v1.ResourceType
	3,  // 24: iam.resource.v1.UpsertResourceRequest.resource:type_name -> iam.resource.v1.Resource
	1,  // 25: iam.resource.v1.UpsertResourceRequest.owner:type_name -> iam.resource.v1.SubjectRef
	0,  // 26: iam.resource.v1.ListResourcesRequest.parent:type_name -> iam.resource.v1.ResourceRef
	29, // 27: iam.resource.v1.ListResourcesRequest.labels:type_name -> iam.resource.v1.ListResourcesRequest.LabelsEntry
	3,  // 28: iam.resource.v1.ListResourcesReply.resources:type_name -> iam.resource.v1.Resource
	0,  // 29: iam.resource.v1.MoveResourceRequest.new_parent:type_name -> iam.resource.v1.ResourceRef
	0,  // 30: iam.resource.v1.DeleteResourceReply.ref:type_name -> iam.resource.v1.ResourceRef
	4,  // 31: iam.resource.v1.BindResourceRequest.binding:type_name -> iam.resource.v1.ResourceBinding
	0,  // 32: iam.resource.v1.ListResourceBindingsRequest.source:type_name -> iam.resource.v1.ResourceRef
	0,  // 33: iam.resource.v1.ListResourceBindingsRequest.target:type_name -> iam.resource.v1.ResourceRef
	4,  // 34: iam.resource.v1.ListResourceBindingsReply.bindings:type_name -> iam.resource.v1.ResourceBinding
	5,  // 35: iam.resource.v1.BindExternalResourceRequest.binding:type_name -> iam.resource.v1.ExternalResourceBinding
	0,  // 36: iam.resource.v1.ListExternalResourceBindingsRequest.resource:type_name -> iam.resource.v1.ResourceRef
	5,  // 37: iam.resource.v1.ListExternalResourceBindingsReply.bindings:type_name -> iam.resource.v1.ExternalResourceBinding
	6,  // 38: iam.resource.v1.ResourceService.RegisterResourceType:input_type -> iam.resource.v1.RegisterResourceTypeRequest
	7,  // 39: iam.resource.v1.ResourceService.GetResourceType:input_type -> iam.resource.v1.GetResourceTypeRequest
	8,  // 40: iam.resource.v1.ResourceService.ListResourceTypes:input_type -> iam.resource.v1.ListResourceTypesRequest
	10, // 41: iam.resource.v1.ResourceService.UpsertResource:input_type -> iam.resource.v1.UpsertResourceRequest
	11, // 42: iam.resource.v1.ResourceService.GetResource:input_type -> iam.resource.v1.GetResourceRequest
	12, // 43: iam.resource.v1.ResourceService.ListResources:input_type -> iam.resource.v1.ListResourcesRequest
	14, // 44: iam.resource.v1.ResourceService.MoveResource:input_type -> iam.resource.v1.MoveResourceRequest
	15, // 45: iam.resource.v1.ResourceService.ArchiveResource:input_type -> iam.resource.v1.ArchiveResourceRequest
	16, // 46: iam.resource.v1.ResourceService.DeleteResource:input_type -> iam.resource.v1.DeleteResourceRequest
	18, // 47: iam.resource.v1.ResourceService.BindResource:input_type -> iam.resource.v1.BindResourceRequest
	19, // 48: iam.resource.v1.ResourceService.UnbindResource:input_type -> iam.resource.v1.UnbindResourceRequest
	21, // 49: iam.resource.v1.ResourceService.ListResourceBindings:input_type -> iam.resource.v1.ListResourceBindingsRequest
	23, // 50: iam.resource.v1.ResourceService.BindExternalResource:input_type -> iam.resource.v1.BindExternalResourceRequest
	24, // 51: iam.resource.v1.ResourceService.ListExternalResourceBindings:input_type -> iam.resource.v1.ListExternalResourceBindingsRequest
	2,  // 52: iam.resource.v1.ResourceService.RegisterResourceType:output_type -> iam.resource.v1.ResourceType
	2,  // 53: iam.resource.v1.ResourceService.GetResourceType:output_type -> iam.resource.v1.ResourceType
	9,  // 54: iam.resource.v1.ResourceService.ListResourceTypes:output_type -> iam.resource.v1.ListResourceTypesReply
	3,  // 55: iam.resource.v1.ResourceService.UpsertResource:output_type -> iam.resource.v1.Resource
	3,  // 56: iam.resource.v1.ResourceService.GetResource:output_type -> iam.resource.v1.Resource
	13, // 57: iam.resource.v1.ResourceService.ListResources:output_type -> iam.resource.v1.ListResourcesReply
	3,  // 58: iam.resource.v1.ResourceService.MoveResource:output_type -> iam.resource.v1.Resource
	3,  // 59: iam.resource.v1.ResourceService.ArchiveResource:output_type -> iam.resource.v1.Resource
	17, // 60: iam.resource.v1.ResourceService.DeleteResource:output_type -> iam.resource.v1.DeleteResourceReply
	4,  // 61: iam.resource.v1.ResourceService.BindResource:output_type -> iam.resource.v1.ResourceBinding
	20, // 62: iam.resource.v1.ResourceService.UnbindResource:output_type -> iam.resource.v1.UnbindResourceReply
	22, // 63: iam.resource.v1.ResourceService.ListResourceBindings:output_type -> iam.resource.v1.ListResourceBindingsReply
	5,  // 64: iam.resource.v1.ResourceService.BindExternalResource:output_type -> iam.resource.v1.ExternalResourceBinding
	25, // 65: iam.resource.v1.ResourceService.ListExternalResourceBindings:output_type -> iam.resource.v1.ListExternalResourceBindingsReply
	52, // [52:66] is the sub-list for method output_type
	38, // [38:52] is the sub-list for method input_type
	38, // [38:38] is the sub-list for extension type_name
	38, // [38:38] is the sub-list for extension extendee
	0,  // [0:38] is the sub-list for field type_name
}

func init() { file_iam_resource_v1_resource_proto_init() }
func file_iam_resource_v1_resource_proto_init() {
	if File_iam_resource_v1_resource_proto != nil {
		return
	}
	file_iam_resource_v1_resource_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_iam_resource_v1_resource_proto_rawDesc), len(file_iam_resource_v1_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_iam_resource_v1_resource_proto_goTypes,
		DependencyIndexes: file_iam_resource_v1_resource_proto_depIdxs,
		MessageInfos:      file_iam_resource_v1_resource_proto_msgTypes,
	}.Build()
	File_iam_resource_v1_resource_proto = out.File
	file_iam_resource_v1_resource_proto_goTypes = nil
	file_iam_resource_v1_resource_proto_depIdxs = nil
}
