// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway v0.2.4-0.20260706010652-0f88c272b4ef
// source: iam/resource/v1/resource.proto

package resourcev1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

// ResourceServiceGatewayManifest returns the generated Gateway route manifest for iam.resource.v1.ResourceService.
func ResourceServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "resource-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "resource.register.resource.type",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/resource-types",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/RegisterResourceType"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.get.resource.type",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/resource-types/{type}",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/GetResourceType"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.list.resource.types",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/resource-types",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/ListResourceTypes"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.upsert.resource",
				Method:   "PUT",
				Path:     "/v1/iam/control-plane/resources",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/UpsertResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.get.resource",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/resources/{resource_type}/{resource_id}",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/GetResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.list.resources",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/resources",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/ListResources"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.move.resource",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/resources/{resource_type}/{resource_id}/move",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/MoveResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.archive.resource",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/resources/{resource_type}/{resource_id}/archive",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/ArchiveResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.delete.resource",
				Method:   "DELETE",
				Path:     "/v1/iam/control-plane/resources/{resource_type}/{resource_id}",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/DeleteResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.bind.resource",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/resource-bindings",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/BindResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.unbind.resource",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/resource-bindings/{binding_id}/unbind",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/UnbindResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.list.resource.bindings",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/resource-bindings",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/ListResourceBindings"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.bind.external.resource",
				Method:   "POST",
				Path:     "/v1/iam/control-plane/external-resource-bindings",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/BindExternalResource"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
			{
				ID:       "resource.list.external.resource.bindings",
				Method:   "GET",
				Path:     "/v1/iam/control-plane/external-resource-bindings",
				Upstream: gatewayx.UpstreamRef{Service: "iam-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/iam.resource.v1.ResourceService/ListExternalResourceBindings"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_AUTHORIZED, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true, Profiles: nil, Tags: nil},
			},
		},
	}
}

// ResourceServiceGatewayBindRegisterResourceType binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/RegisterResourceType.
func ResourceServiceGatewayBindRegisterResourceType(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*RegisterResourceTypeRequest, error) {
	out := &RegisterResourceTypeRequest{}
	if v, ok := req.Body.(*RegisterResourceTypeRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(RegisterResourceTypeRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindGetResourceType binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/GetResourceType.
func ResourceServiceGatewayBindGetResourceType(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetResourceTypeRequest, error) {
	out := &GetResourceTypeRequest{}
	if v, ok := req.Body.(*GetResourceTypeRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetResourceTypeRequest); ok {
		out = &v
	}
	if v := match.Params["type"]; v != "" {
		out.Type = v
	}
	return out, nil
}

// ResourceServiceGatewayBindListResourceTypes binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/ListResourceTypes.
func ResourceServiceGatewayBindListResourceTypes(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListResourceTypesRequest, error) {
	out := &ListResourceTypesRequest{}
	if v, ok := req.Body.(*ListResourceTypesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListResourceTypesRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindUpsertResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/UpsertResource.
func ResourceServiceGatewayBindUpsertResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UpsertResourceRequest, error) {
	out := &UpsertResourceRequest{}
	if v, ok := req.Body.(*UpsertResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UpsertResourceRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindGetResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/GetResource.
func ResourceServiceGatewayBindGetResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetResourceRequest, error) {
	out := &GetResourceRequest{}
	if v, ok := req.Body.(*GetResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetResourceRequest); ok {
		out = &v
	}
	if v := match.Params["resource_type"]; v != "" {
		out.ResourceType = v
	}
	if v := match.Params["resource_id"]; v != "" {
		out.ResourceId = v
	}
	return out, nil
}

// ResourceServiceGatewayBindListResources binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/ListResources.
func ResourceServiceGatewayBindListResources(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListResourcesRequest, error) {
	out := &ListResourcesRequest{}
	if v, ok := req.Body.(*ListResourcesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListResourcesRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindMoveResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/MoveResource.
func ResourceServiceGatewayBindMoveResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*MoveResourceRequest, error) {
	out := &MoveResourceRequest{}
	if v, ok := req.Body.(*MoveResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(MoveResourceRequest); ok {
		out = &v
	}
	if v := match.Params["resource_type"]; v != "" {
		out.ResourceType = v
	}
	if v := match.Params["resource_id"]; v != "" {
		out.ResourceId = v
	}
	return out, nil
}

// ResourceServiceGatewayBindArchiveResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/ArchiveResource.
func ResourceServiceGatewayBindArchiveResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ArchiveResourceRequest, error) {
	out := &ArchiveResourceRequest{}
	if v, ok := req.Body.(*ArchiveResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ArchiveResourceRequest); ok {
		out = &v
	}
	if v := match.Params["resource_type"]; v != "" {
		out.ResourceType = v
	}
	if v := match.Params["resource_id"]; v != "" {
		out.ResourceId = v
	}
	return out, nil
}

// ResourceServiceGatewayBindDeleteResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/DeleteResource.
func ResourceServiceGatewayBindDeleteResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*DeleteResourceRequest, error) {
	out := &DeleteResourceRequest{}
	if v, ok := req.Body.(*DeleteResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(DeleteResourceRequest); ok {
		out = &v
	}
	if v := match.Params["resource_type"]; v != "" {
		out.ResourceType = v
	}
	if v := match.Params["resource_id"]; v != "" {
		out.ResourceId = v
	}
	return out, nil
}

// ResourceServiceGatewayBindBindResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/BindResource.
func ResourceServiceGatewayBindBindResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*BindResourceRequest, error) {
	out := &BindResourceRequest{}
	if v, ok := req.Body.(*BindResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(BindResourceRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindUnbindResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/UnbindResource.
func ResourceServiceGatewayBindUnbindResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*UnbindResourceRequest, error) {
	out := &UnbindResourceRequest{}
	if v, ok := req.Body.(*UnbindResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(UnbindResourceRequest); ok {
		out = &v
	}
	if v := match.Params["binding_id"]; v != "" {
		out.BindingId = v
	}
	return out, nil
}

// ResourceServiceGatewayBindListResourceBindings binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/ListResourceBindings.
func ResourceServiceGatewayBindListResourceBindings(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListResourceBindingsRequest, error) {
	out := &ListResourceBindingsRequest{}
	if v, ok := req.Body.(*ListResourceBindingsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListResourceBindingsRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindBindExternalResource binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/BindExternalResource.
func ResourceServiceGatewayBindBindExternalResource(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*BindExternalResourceRequest, error) {
	out := &BindExternalResourceRequest{}
	if v, ok := req.Body.(*BindExternalResourceRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(BindExternalResourceRequest); ok {
		out = &v
	}
	return out, nil
}

// ResourceServiceGatewayBindListExternalResourceBindings binds the matched HTTP Gateway request to the gRPC request for /iam.resource.v1.ResourceService/ListExternalResourceBindings.
func ResourceServiceGatewayBindListExternalResourceBindings(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ListExternalResourceBindingsRequest, error) {
	out := &ListExternalResourceBindingsRequest{}
	if v, ok := req.Body.(*ListExternalResourceBindingsRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ListExternalResourceBindingsRequest); ok {
		out = &v
	}
	return out, nil
}

// RegisterResourceServiceGatewayInvokers registers generated Gateway -> gRPC operation invokers for iam.resource.v1.ResourceService.
func RegisterResourceServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client ResourceServiceClient) error {
	if err := registry.Register("/iam.resource.v1.ResourceService/RegisterResourceType", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindRegisterResourceType, client.RegisterResourceType)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/GetResourceType", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindGetResourceType, client.GetResourceType)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/ListResourceTypes", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindListResourceTypes, client.ListResourceTypes)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/UpsertResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindUpsertResource, client.UpsertResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/GetResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindGetResource, client.GetResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/ListResources", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindListResources, client.ListResources)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/MoveResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindMoveResource, client.MoveResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/ArchiveResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindArchiveResource, client.ArchiveResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/DeleteResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindDeleteResource, client.DeleteResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/BindResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindBindResource, client.BindResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/UnbindResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindUnbindResource, client.UnbindResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/ListResourceBindings", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindListResourceBindings, client.ListResourceBindings)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/BindExternalResource", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindBindExternalResource, client.BindExternalResource)); err != nil {
		return err
	}
	if err := registry.Register("/iam.resource.v1.ResourceService/ListExternalResourceBindings", gatewayx.GRPCUnaryInvoker(ResourceServiceGatewayBindListExternalResourceBindings, client.ListExternalResourceBindings)); err != nil {
		return err
	}
	return nil
}
