apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: iam-http
  namespace: aisphere
spec:
  parentRefs:
    - name: aisphere-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/iam
      backendRefs:
        - name: aisphere-iam
          port: 18080
    - matches:
        - path:
            type: Exact
            value: /healthz
        - path:
            type: Exact
            value: /readyz
      backendRefs:
        - name: aisphere-iam
          port: 18080
