// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.1
// source: iam/v1/iam.proto

package v1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// IAMAuthServiceKernelModule returns the generated Kernel service module for iam.v1.IAMAuthService.
func IAMAuthServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.auth-service",
		GatewayManifest:     IAMAuthServiceGatewayManifest(),
		RequestInfoResolver: IAMAuthServiceKernelRequestInfoResolver,
		AccessResolver:      IAMAuthServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMAuthServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMAuthService must implement IAMAuthServiceServer, got %T", impl)
			}
			RegisterIAMAuthServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMAuthServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMAuthService must implement IAMAuthServiceHTTPServer, got %T", impl)
			}
			RegisterIAMAuthServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMAuthServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMAuthService must implement IAMAuthServiceClient, got %T", client)
			}
			return RegisterIAMAuthServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMAuthServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMAuthService/VerifyToken": {
		Service:    "iam.v1.IAMAuthService",
		Method:     "VerifyToken",
		FullMethod: "/iam.v1.IAMAuthService/VerifyToken",
		Action:     "verify",
		Resource:   "iam:token",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.verify_token",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMAuthService/GetMe": {
		Service:    "iam.v1.IAMAuthService",
		Method:     "GetMe",
		FullMethod: "/iam.v1.IAMAuthService/GetMe",
		Action:     "read",
		Resource:   "iam:self",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.get_me",
		AuditRisk:  "low",
	},
}

// IAMAuthServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMAuthServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMAuthServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMAuthService/VerifyToken":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthService",
			Method:        "VerifyToken",
			Operation:     "/iam.v1.IAMAuthService/VerifyToken",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "verify",
			Resource:      "iam:token",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.verify_token"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthService/GetMe":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthService",
			Method:        "GetMe",
			Operation:     "/iam.v1.IAMAuthService/GetMe",
			Exposure:      v1.Exposure_AUTHENTICATED,
			Action:        "read",
			Resource:      "iam:self",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.get_me"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMAuthServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMAuthServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMAuthServiceKernelAuthzRules[_IAMAuthServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMAuthServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "VerifyToken", "iam.v1.IAMAuthService/VerifyToken":
		return "/iam.v1.IAMAuthService/VerifyToken"
	case "GetMe", "iam.v1.IAMAuthService/GetMe":
		return "/iam.v1.IAMAuthService/GetMe"
	default:
		return operation
	}
}

// IAMDirectoryServiceKernelModule returns the generated Kernel service module for iam.v1.IAMDirectoryService.
func IAMDirectoryServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.directory-service",
		GatewayManifest:     IAMDirectoryServiceGatewayManifest(),
		RequestInfoResolver: IAMDirectoryServiceKernelRequestInfoResolver,
		AccessResolver:      IAMDirectoryServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMDirectoryServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMDirectoryService must implement IAMDirectoryServiceServer, got %T", impl)
			}
			RegisterIAMDirectoryServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMDirectoryServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMDirectoryService must implement IAMDirectoryServiceHTTPServer, got %T", impl)
			}
			RegisterIAMDirectoryServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMDirectoryServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMDirectoryService must implement IAMDirectoryServiceClient, got %T", client)
			}
			return RegisterIAMDirectoryServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMDirectoryServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMDirectoryService/GetUser": {
		Service:    "iam.v1.IAMDirectoryService",
		Method:     "GetUser",
		FullMethod: "/iam.v1.IAMDirectoryService/GetUser",
		Action:     "view_users",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.user.get",
		AuditRisk:  "low",
	},
	"/iam.v1.IAMDirectoryService/ListUsers": {
		Service:    "iam.v1.IAMDirectoryService",
		Method:     "ListUsers",
		FullMethod: "/iam.v1.IAMDirectoryService/ListUsers",
		Action:     "view_users",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.user.list",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMDirectoryService/GetOrganization": {
		Service:    "iam.v1.IAMDirectoryService",
		Method:     "GetOrganization",
		FullMethod: "/iam.v1.IAMDirectoryService/GetOrganization",
		Action:     "view_zone",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.org.get",
		AuditRisk:  "low",
	},
	"/iam.v1.IAMDirectoryService/ListGroups": {
		Service:    "iam.v1.IAMDirectoryService",
		Method:     "ListGroups",
		FullMethod: "/iam.v1.IAMDirectoryService/ListGroups",
		Action:     "view_groups",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.group.list",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMDirectoryService/GetGroup": {
		Service:    "iam.v1.IAMDirectoryService",
		Method:     "GetGroup",
		FullMethod: "/iam.v1.IAMDirectoryService/GetGroup",
		Action:     "view_groups",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.group.get",
		AuditRisk:  "low",
	},
}

// IAMDirectoryServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMDirectoryServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMDirectoryServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMDirectoryService/GetUser":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryService",
			Method:        "GetUser",
			Operation:     "/iam.v1.IAMDirectoryService/GetUser",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_users",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.user.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryService/ListUsers":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryService",
			Method:        "ListUsers",
			Operation:     "/iam.v1.IAMDirectoryService/ListUsers",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_users",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.user.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryService/GetOrganization":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryService",
			Method:        "GetOrganization",
			Operation:     "/iam.v1.IAMDirectoryService/GetOrganization",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_zone",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.org.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryService/ListGroups":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryService",
			Method:        "ListGroups",
			Operation:     "/iam.v1.IAMDirectoryService/ListGroups",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_groups",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.group.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryService/GetGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryService",
			Method:        "GetGroup",
			Operation:     "/iam.v1.IAMDirectoryService/GetGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_groups",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.group.get"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMDirectoryServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMDirectoryServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMDirectoryServiceKernelAuthzRules[_IAMDirectoryServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMDirectoryServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "GetUser", "iam.v1.IAMDirectoryService/GetUser":
		return "/iam.v1.IAMDirectoryService/GetUser"
	case "ListUsers", "iam.v1.IAMDirectoryService/ListUsers":
		return "/iam.v1.IAMDirectoryService/ListUsers"
	case "GetOrganization", "iam.v1.IAMDirectoryService/GetOrganization":
		return "/iam.v1.IAMDirectoryService/GetOrganization"
	case "ListGroups", "iam.v1.IAMDirectoryService/ListGroups":
		return "/iam.v1.IAMDirectoryService/ListGroups"
	case "GetGroup", "iam.v1.IAMDirectoryService/GetGroup":
		return "/iam.v1.IAMDirectoryService/GetGroup"
	default:
		return operation
	}
}

// IAMDirectoryProjectionServiceKernelModule returns the generated Kernel service module for iam.v1.IAMDirectoryProjectionService.
func IAMDirectoryProjectionServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.directory.projection-service",
		GatewayManifest:     IAMDirectoryProjectionServiceGatewayManifest(),
		RequestInfoResolver: IAMDirectoryProjectionServiceKernelRequestInfoResolver,
		AccessResolver:      IAMDirectoryProjectionServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMDirectoryProjectionServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMDirectoryProjectionService must implement IAMDirectoryProjectionServiceServer, got %T", impl)
			}
			RegisterIAMDirectoryProjectionServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMDirectoryProjectionServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMDirectoryProjectionService must implement IAMDirectoryProjectionServiceHTTPServer, got %T", impl)
			}
			RegisterIAMDirectoryProjectionServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMDirectoryProjectionServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMDirectoryProjectionService must implement IAMDirectoryProjectionServiceClient, got %T", client)
			}
			return RegisterIAMDirectoryProjectionServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMDirectoryProjectionServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection": {
		Service:    "iam.v1.IAMDirectoryProjectionService",
		Method:     "RetryDirectoryProjection",
		FullMethod: "/iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection",
		Action:     "repair_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.directory_projection.retry",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection": {
		Service:    "iam.v1.IAMDirectoryProjectionService",
		Method:     "ReconcileDirectoryProjection",
		FullMethod: "/iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection",
		Action:     "repair_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.directory_projection.reconcile",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift": {
		Service:    "iam.v1.IAMDirectoryProjectionService",
		Method:     "CheckDirectoryProjectionDrift",
		FullMethod: "/iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift",
		Action:     "view_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.directory_projection.drift",
		AuditRisk:  "medium",
	},
}

// IAMDirectoryProjectionServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMDirectoryProjectionServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMDirectoryProjectionServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryProjectionService",
			Method:        "RetryDirectoryProjection",
			Operation:     "/iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "repair_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.directory_projection.retry"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryProjectionService",
			Method:        "ReconcileDirectoryProjection",
			Operation:     "/iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "repair_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.directory_projection.reconcile"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift":
		info := requestx.Info{
			Service:       "iam.v1.IAMDirectoryProjectionService",
			Method:        "CheckDirectoryProjectionDrift",
			Operation:     "/iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.directory_projection.drift"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMDirectoryProjectionServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMDirectoryProjectionServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMDirectoryProjectionServiceKernelAuthzRules[_IAMDirectoryProjectionServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMDirectoryProjectionServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "RetryDirectoryProjection", "iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection":
		return "/iam.v1.IAMDirectoryProjectionService/RetryDirectoryProjection"
	case "ReconcileDirectoryProjection", "iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection":
		return "/iam.v1.IAMDirectoryProjectionService/ReconcileDirectoryProjection"
	case "CheckDirectoryProjectionDrift", "iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift":
		return "/iam.v1.IAMDirectoryProjectionService/CheckDirectoryProjectionDrift"
	default:
		return operation
	}
}

// IAMPermissionServiceKernelModule returns the generated Kernel service module for iam.v1.IAMPermissionService.
func IAMPermissionServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.permission-service",
		GatewayManifest:     IAMPermissionServiceGatewayManifest(),
		RequestInfoResolver: IAMPermissionServiceKernelRequestInfoResolver,
		AccessResolver:      IAMPermissionServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMPermissionServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMPermissionService must implement IAMPermissionServiceServer, got %T", impl)
			}
			RegisterIAMPermissionServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMPermissionServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMPermissionService must implement IAMPermissionServiceHTTPServer, got %T", impl)
			}
			RegisterIAMPermissionServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMPermissionServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMPermissionService must implement IAMPermissionServiceClient, got %T", client)
			}
			return RegisterIAMPermissionServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMPermissionServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMPermissionService/CheckPermission": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "CheckPermission",
		FullMethod: "/iam.v1.IAMPermissionService/CheckPermission",
		Action:     "check",
		Resource:   "iam:permission",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.permission.check",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMPermissionService/BatchCheckPermissions": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "BatchCheckPermissions",
		FullMethod: "/iam.v1.IAMPermissionService/BatchCheckPermissions",
		Action:     "check",
		Resource:   "iam:permission",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.permission.batch_check",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMPermissionService/WriteRelationships": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "WriteRelationships",
		FullMethod: "/iam.v1.IAMPermissionService/WriteRelationships",
		Action:     "write",
		Resource:   "iam:relationship",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.relationship.batch_write",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMPermissionService/DeleteRelationships": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "DeleteRelationships",
		FullMethod: "/iam.v1.IAMPermissionService/DeleteRelationships",
		Action:     "delete",
		Resource:   "iam:relationship",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.relationship.batch_delete",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMPermissionService/ReadRelationships": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "ReadRelationships",
		FullMethod: "/iam.v1.IAMPermissionService/ReadRelationships",
		Action:     "read",
		Resource:   "iam:relationship",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.relationship.read",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMPermissionService/LookupResources": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "LookupResources",
		FullMethod: "/iam.v1.IAMPermissionService/LookupResources",
		Action:     "lookup",
		Resource:   "iam:resource",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.resource.lookup",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMPermissionService/LookupSubjects": {
		Service:    "iam.v1.IAMPermissionService",
		Method:     "LookupSubjects",
		FullMethod: "/iam.v1.IAMPermissionService/LookupSubjects",
		Action:     "lookup",
		Resource:   "iam:subject",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.subject.lookup",
		AuditRisk:  "medium",
	},
}

// IAMPermissionServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMPermissionServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMPermissionServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMPermissionService/CheckPermission":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "CheckPermission",
			Operation:     "/iam.v1.IAMPermissionService/CheckPermission",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "check",
			Resource:      "iam:permission",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.permission.check"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/BatchCheckPermissions":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "BatchCheckPermissions",
			Operation:     "/iam.v1.IAMPermissionService/BatchCheckPermissions",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "check",
			Resource:      "iam:permission",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.permission.batch_check"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/WriteRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "WriteRelationships",
			Operation:     "/iam.v1.IAMPermissionService/WriteRelationships",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "write",
			Resource:      "iam:relationship",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.relationship.batch_write"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/DeleteRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "DeleteRelationships",
			Operation:     "/iam.v1.IAMPermissionService/DeleteRelationships",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "delete",
			Resource:      "iam:relationship",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.relationship.batch_delete"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/ReadRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "ReadRelationships",
			Operation:     "/iam.v1.IAMPermissionService/ReadRelationships",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "read",
			Resource:      "iam:relationship",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.relationship.read"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/LookupResources":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "LookupResources",
			Operation:     "/iam.v1.IAMPermissionService/LookupResources",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "lookup",
			Resource:      "iam:resource",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.resource.lookup"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMPermissionService/LookupSubjects":
		info := requestx.Info{
			Service:       "iam.v1.IAMPermissionService",
			Method:        "LookupSubjects",
			Operation:     "/iam.v1.IAMPermissionService/LookupSubjects",
			Exposure:      v1.Exposure_INTERNAL,
			Action:        "lookup",
			Resource:      "iam:subject",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.subject.lookup"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMPermissionServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMPermissionServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMPermissionServiceKernelAuthzRules[_IAMPermissionServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMPermissionServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CheckPermission", "iam.v1.IAMPermissionService/CheckPermission":
		return "/iam.v1.IAMPermissionService/CheckPermission"
	case "BatchCheckPermissions", "iam.v1.IAMPermissionService/BatchCheckPermissions":
		return "/iam.v1.IAMPermissionService/BatchCheckPermissions"
	case "WriteRelationships", "iam.v1.IAMPermissionService/WriteRelationships":
		return "/iam.v1.IAMPermissionService/WriteRelationships"
	case "DeleteRelationships", "iam.v1.IAMPermissionService/DeleteRelationships":
		return "/iam.v1.IAMPermissionService/DeleteRelationships"
	case "ReadRelationships", "iam.v1.IAMPermissionService/ReadRelationships":
		return "/iam.v1.IAMPermissionService/ReadRelationships"
	case "LookupResources", "iam.v1.IAMPermissionService/LookupResources":
		return "/iam.v1.IAMPermissionService/LookupResources"
	case "LookupSubjects", "iam.v1.IAMPermissionService/LookupSubjects":
		return "/iam.v1.IAMPermissionService/LookupSubjects"
	default:
		return operation
	}
}

// IAMAuthorizationAdminServiceKernelModule returns the generated Kernel service module for iam.v1.IAMAuthorizationAdminService.
func IAMAuthorizationAdminServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.authorization.admin-service",
		GatewayManifest:     IAMAuthorizationAdminServiceGatewayManifest(),
		RequestInfoResolver: IAMAuthorizationAdminServiceKernelRequestInfoResolver,
		AccessResolver:      IAMAuthorizationAdminServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMAuthorizationAdminServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMAuthorizationAdminService must implement IAMAuthorizationAdminServiceServer, got %T", impl)
			}
			RegisterIAMAuthorizationAdminServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMAuthorizationAdminServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMAuthorizationAdminService must implement IAMAuthorizationAdminServiceHTTPServer, got %T", impl)
			}
			RegisterIAMAuthorizationAdminServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMAuthorizationAdminServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMAuthorizationAdminService must implement IAMAuthorizationAdminServiceClient, got %T", client)
			}
			return RegisterIAMAuthorizationAdminServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMAuthorizationAdminServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "GetAuthorizationSchema",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema",
		Action:     "view_schema",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.schema.get",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "ValidateAuthorizationSchema",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema",
		Action:     "publish_schema",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.schema.validate",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "PublishAuthorizationSchema",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema",
		Action:     "publish_schema",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.schema.publish",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMAuthorizationAdminService/ListRelationships": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "ListRelationships",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/ListRelationships",
		Action:     "view_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.relationship.list",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMAuthorizationAdminService/WriteRelationships": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "WriteRelationships",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/WriteRelationships",
		Action:     "repair_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.relationship.write",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMAuthorizationAdminService/DeleteRelationships": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "DeleteRelationships",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/DeleteRelationships",
		Action:     "repair_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.relationship.delete",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMAuthorizationAdminService/CheckAuthorization": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "CheckAuthorization",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/CheckAuthorization",
		Action:     "view_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.permission.check",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMAuthorizationAdminService/ExplainAuthorization": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "ExplainAuthorization",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/ExplainAuthorization",
		Action:     "view_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.permission.explain",
		AuditRisk:  "medium",
	},
	"/iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions": {
		Service:    "iam.v1.IAMAuthorizationAdminService",
		Method:     "GetEffectivePermissions",
		FullMethod: "/iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions",
		Action:     "view_relationships",
		Resource:   "iam_authz:global",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("SELF_CHECK"),
		AuditEvent: "iam.authz.effective_permissions",
		AuditRisk:  "medium",
	},
}

// IAMAuthorizationAdminServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMAuthorizationAdminServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMAuthorizationAdminServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "GetAuthorizationSchema",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_schema",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.schema.get"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "ValidateAuthorizationSchema",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "publish_schema",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.schema.validate"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "PublishAuthorizationSchema",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "publish_schema",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.schema.publish"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/ListRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "ListRelationships",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/ListRelationships",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.relationship.list"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/WriteRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "WriteRelationships",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/WriteRelationships",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "repair_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.relationship.write"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/DeleteRelationships":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "DeleteRelationships",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/DeleteRelationships",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "repair_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.relationship.delete"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/CheckAuthorization":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "CheckAuthorization",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/CheckAuthorization",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.permission.check"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/ExplainAuthorization":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "ExplainAuthorization",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/ExplainAuthorization",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.permission.explain"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions":
		info := requestx.Info{
			Service:       "iam.v1.IAMAuthorizationAdminService",
			Method:        "GetEffectivePermissions",
			Operation:     "/iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "view_relationships",
			Resource:      "iam_authz:global",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "SELF_CHECK"
		info.Labels["audit_event"] = "iam.authz.effective_permissions"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMAuthorizationAdminServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMAuthorizationAdminServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMAuthorizationAdminServiceKernelAuthzRules[_IAMAuthorizationAdminServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMAuthorizationAdminServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "GetAuthorizationSchema", "iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema":
		return "/iam.v1.IAMAuthorizationAdminService/GetAuthorizationSchema"
	case "ValidateAuthorizationSchema", "iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema":
		return "/iam.v1.IAMAuthorizationAdminService/ValidateAuthorizationSchema"
	case "PublishAuthorizationSchema", "iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema":
		return "/iam.v1.IAMAuthorizationAdminService/PublishAuthorizationSchema"
	case "ListRelationships", "iam.v1.IAMAuthorizationAdminService/ListRelationships":
		return "/iam.v1.IAMAuthorizationAdminService/ListRelationships"
	case "WriteRelationships", "iam.v1.IAMAuthorizationAdminService/WriteRelationships":
		return "/iam.v1.IAMAuthorizationAdminService/WriteRelationships"
	case "DeleteRelationships", "iam.v1.IAMAuthorizationAdminService/DeleteRelationships":
		return "/iam.v1.IAMAuthorizationAdminService/DeleteRelationships"
	case "CheckAuthorization", "iam.v1.IAMAuthorizationAdminService/CheckAuthorization":
		return "/iam.v1.IAMAuthorizationAdminService/CheckAuthorization"
	case "ExplainAuthorization", "iam.v1.IAMAuthorizationAdminService/ExplainAuthorization":
		return "/iam.v1.IAMAuthorizationAdminService/ExplainAuthorization"
	case "GetEffectivePermissions", "iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions":
		return "/iam.v1.IAMAuthorizationAdminService/GetEffectivePermissions"
	default:
		return operation
	}
}
