// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.4.1
// source: iam/v1/identity_admin.proto

package v1

import (
	context "context"
	fmt "fmt"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
	grpc "github.com/aisphereio/kernel/transportx/grpc"
	http "github.com/aisphereio/kernel/transportx/http"
)

// IAMIdentityAdminServiceKernelModule returns the generated Kernel service module for iam.v1.IAMIdentityAdminService.
func IAMIdentityAdminServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "i.a.m.identity.admin-service",
		GatewayManifest:     IAMIdentityAdminServiceGatewayManifest(),
		RequestInfoResolver: IAMIdentityAdminServiceKernelRequestInfoResolver,
		AccessResolver:      IAMIdentityAdminServiceKernelAccessResolver,
		RegisterGRPC: func(s *grpc.Server, impl any) error {
			typed, ok := impl.(IAMIdentityAdminServiceServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMIdentityAdminService must implement IAMIdentityAdminServiceServer, got %T", impl)
			}
			RegisterIAMIdentityAdminServiceServer(s, typed)
			return nil
		},
		RegisterHTTP: func(s *http.Server, impl any) error {
			typed, ok := impl.(IAMIdentityAdminServiceHTTPServer)
			if !ok {
				return fmt.Errorf("serverx: service implementation for iam.v1.IAMIdentityAdminService must implement IAMIdentityAdminServiceHTTPServer, got %T", impl)
			}
			RegisterIAMIdentityAdminServiceHTTPServer(s, typed)
			return nil
		},
		RegisterGatewayInvokers: func(r *gatewayx.InvokerRegistry, client any) error {
			typed, ok := client.(IAMIdentityAdminServiceClient)
			if !ok {
				return fmt.Errorf("serverx: gateway client for iam.v1.IAMIdentityAdminService must implement IAMIdentityAdminServiceClient, got %T", client)
			}
			return RegisterIAMIdentityAdminServiceGatewayInvokers(r, typed)
		},
	}
}

var IAMIdentityAdminServiceKernelAuthzRules = authz.Rules{
	"/iam.v1.IAMIdentityAdminService/CreateUser": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "CreateUser",
		FullMethod: "/iam.v1.IAMIdentityAdminService/CreateUser",
		Action:     "create",
		Resource:   "iam:org:{org_id}:user:*",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.user.create",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/UpdateUser": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "UpdateUser",
		FullMethod: "/iam.v1.IAMIdentityAdminService/UpdateUser",
		Action:     "update",
		Resource:   "iam:org:{org_id}:user:{user_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.user.update",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/DisableUser": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "DisableUser",
		FullMethod: "/iam.v1.IAMIdentityAdminService/DisableUser",
		Action:     "disable",
		Resource:   "iam:org:{org_id}:user:{user_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.user.disable",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/DeleteUser": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "DeleteUser",
		FullMethod: "/iam.v1.IAMIdentityAdminService/DeleteUser",
		Action:     "delete",
		Resource:   "iam:org:{org_id}:user:{user_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.user.delete",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMIdentityAdminService/CreateGroup": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "CreateGroup",
		FullMethod: "/iam.v1.IAMIdentityAdminService/CreateGroup",
		Action:     "create_groups",
		Resource:   "zone:{org_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.group.create",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/UpdateGroup": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "UpdateGroup",
		FullMethod: "/iam.v1.IAMIdentityAdminService/UpdateGroup",
		Action:     "manage",
		Resource:   "group:{org_id}/{group_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.group.update",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/DeleteGroup": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "DeleteGroup",
		FullMethod: "/iam.v1.IAMIdentityAdminService/DeleteGroup",
		Action:     "manage",
		Resource:   "group:{org_id}/{group_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.group.delete",
		AuditRisk:  "critical",
	},
	"/iam.v1.IAMIdentityAdminService/AssignUserToGroup": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "AssignUserToGroup",
		FullMethod: "/iam.v1.IAMIdentityAdminService/AssignUserToGroup",
		Action:     "manage",
		Resource:   "group:{org_id}/{group_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.group.user.assign",
		AuditRisk:  "high",
	},
	"/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup": {
		Service:    "iam.v1.IAMIdentityAdminService",
		Method:     "RemoveUserFromGroup",
		FullMethod: "/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup",
		Action:     "manage",
		Resource:   "group:{org_id}/{group_id}",
		Audience:   "iam-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "iam.group.user.remove",
		AuditRisk:  "high",
	},
}

// IAMIdentityAdminServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func IAMIdentityAdminServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _IAMIdentityAdminServiceKernelNormalizeOperation(operation) {
	case "/iam.v1.IAMIdentityAdminService/CreateUser":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "CreateUser",
			Operation:     "/iam.v1.IAMIdentityAdminService/CreateUser",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "create",
			Resource:      "iam:org:{org_id}:user:*",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.user.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/UpdateUser":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "UpdateUser",
			Operation:     "/iam.v1.IAMIdentityAdminService/UpdateUser",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "update",
			Resource:      "iam:org:{org_id}:user:{user_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.user.update"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/DisableUser":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "DisableUser",
			Operation:     "/iam.v1.IAMIdentityAdminService/DisableUser",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "disable",
			Resource:      "iam:org:{org_id}:user:{user_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.user.disable"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/DeleteUser":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "DeleteUser",
			Operation:     "/iam.v1.IAMIdentityAdminService/DeleteUser",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "delete",
			Resource:      "iam:org:{org_id}:user:{user_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.user.delete"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/CreateGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "CreateGroup",
			Operation:     "/iam.v1.IAMIdentityAdminService/CreateGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "create_groups",
			Resource:      "zone:{org_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.group.create"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/UpdateGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "UpdateGroup",
			Operation:     "/iam.v1.IAMIdentityAdminService/UpdateGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "group:{org_id}/{group_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.group.update"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/DeleteGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "DeleteGroup",
			Operation:     "/iam.v1.IAMIdentityAdminService/DeleteGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "group:{org_id}/{group_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.group.delete"
		info.Labels["audit_risk"] = "critical"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/AssignUserToGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "AssignUserToGroup",
			Operation:     "/iam.v1.IAMIdentityAdminService/AssignUserToGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "group:{org_id}/{group_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.group.user.assign"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	case "/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup":
		info := requestx.Info{
			Service:       "iam.v1.IAMIdentityAdminService",
			Method:        "RemoveUserFromGroup",
			Operation:     "/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup",
			Exposure:      v1.Exposure_AUTHORIZED,
			Action:        "manage",
			Resource:      "group:{org_id}/{group_id}",
			TargetService: "iam-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "iam.group.user.remove"
		info.Labels["audit_risk"] = "high"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// IAMIdentityAdminServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func IAMIdentityAdminServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := IAMIdentityAdminServiceKernelAuthzRules[_IAMIdentityAdminServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _IAMIdentityAdminServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "CreateUser", "iam.v1.IAMIdentityAdminService/CreateUser":
		return "/iam.v1.IAMIdentityAdminService/CreateUser"
	case "UpdateUser", "iam.v1.IAMIdentityAdminService/UpdateUser":
		return "/iam.v1.IAMIdentityAdminService/UpdateUser"
	case "DisableUser", "iam.v1.IAMIdentityAdminService/DisableUser":
		return "/iam.v1.IAMIdentityAdminService/DisableUser"
	case "DeleteUser", "iam.v1.IAMIdentityAdminService/DeleteUser":
		return "/iam.v1.IAMIdentityAdminService/DeleteUser"
	case "CreateGroup", "iam.v1.IAMIdentityAdminService/CreateGroup":
		return "/iam.v1.IAMIdentityAdminService/CreateGroup"
	case "UpdateGroup", "iam.v1.IAMIdentityAdminService/UpdateGroup":
		return "/iam.v1.IAMIdentityAdminService/UpdateGroup"
	case "DeleteGroup", "iam.v1.IAMIdentityAdminService/DeleteGroup":
		return "/iam.v1.IAMIdentityAdminService/DeleteGroup"
	case "AssignUserToGroup", "iam.v1.IAMIdentityAdminService/AssignUserToGroup":
		return "/iam.v1.IAMIdentityAdminService/AssignUserToGroup"
	case "RemoveUserFromGroup", "iam.v1.IAMIdentityAdminService/RemoveUserFromGroup":
		return "/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup"
	default:
		return operation
	}
}
