// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.4.3
// - protoc             (unknown)
// source: iam/v1/identity_admin.proto

package v1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationIAMIdentityAdminServiceAssignUserToGroup = "/iam.v1.IAMIdentityAdminService/AssignUserToGroup"
const OperationIAMIdentityAdminServiceCreateGroup = "/iam.v1.IAMIdentityAdminService/CreateGroup"
const OperationIAMIdentityAdminServiceCreateUser = "/iam.v1.IAMIdentityAdminService/CreateUser"
const OperationIAMIdentityAdminServiceDeleteGroup = "/iam.v1.IAMIdentityAdminService/DeleteGroup"
const OperationIAMIdentityAdminServiceDeleteUser = "/iam.v1.IAMIdentityAdminService/DeleteUser"
const OperationIAMIdentityAdminServiceDisableUser = "/iam.v1.IAMIdentityAdminService/DisableUser"
const OperationIAMIdentityAdminServiceRemoveUserFromGroup = "/iam.v1.IAMIdentityAdminService/RemoveUserFromGroup"
const OperationIAMIdentityAdminServiceUpdateGroup = "/iam.v1.IAMIdentityAdminService/UpdateGroup"
const OperationIAMIdentityAdminServiceUpdateUser = "/iam.v1.IAMIdentityAdminService/UpdateUser"

type IAMIdentityAdminServiceHTTPServer interface {
	AssignUserToGroup(context.Context, *AssignUserToGroupRequest) (*emptypb.Empty, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*Group, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*emptypb.Empty, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	DisableUser(context.Context, *DisableUserRequest) (*emptypb.Empty, error)
	RemoveUserFromGroup(context.Context, *RemoveUserFromGroupRequest) (*emptypb.Empty, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*Group, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
}

func RegisterIAMIdentityAdminServiceHTTPServer(s *http.Server, srv IAMIdentityAdminServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("DELETE", "/v1/iam/orgs/{org_id}/groups/{group_id}", _IAMIdentityAdminService_DeleteGroup0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/iam/orgs/{org_id}/users/{user_id}", _IAMIdentityAdminService_DeleteUser0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/iam/orgs/{org_id}/groups/{group_id}/users/{user_id}", _IAMIdentityAdminService_RemoveUserFromGroup0_HTTP_Handler(srv))
	r.Handle("PATCH", "/v1/iam/orgs/{org_id}/groups/{group_id}", _IAMIdentityAdminService_UpdateGroup0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/groups", _IAMIdentityAdminService_CreateGroup0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/users", _IAMIdentityAdminService_CreateUser0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/users/{user_id}:disable", _IAMIdentityAdminService_DisableUser0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/iam/orgs/{org_id}/groups/{group_id}/users/{user_id}", _IAMIdentityAdminService_AssignUserToGroup0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/iam/orgs/{org_id}/users/{user_id}", _IAMIdentityAdminService_UpdateUser0_HTTP_Handler(srv))
}

func _IAMIdentityAdminService_DeleteGroup0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceDeleteGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGroup(ctx, req.(*DeleteGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_DeleteUser0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteUserRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceDeleteUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUser(ctx, req.(*DeleteUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_RemoveUserFromGroup0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveUserFromGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceRemoveUserFromGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveUserFromGroup(ctx, req.(*RemoveUserFromGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_UpdateGroup0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceUpdateGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGroup(ctx, req.(*UpdateGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Group)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_CreateGroup0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceCreateGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGroup(ctx, req.(*CreateGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Group)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_CreateUser0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceCreateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUser(ctx, req.(*CreateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_DisableUser0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DisableUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceDisableUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DisableUser(ctx, req.(*DisableUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_AssignUserToGroup0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignUserToGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceAssignUserToGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignUserToGroup(ctx, req.(*AssignUserToGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _IAMIdentityAdminService_UpdateUser0_HTTP_Handler(srv IAMIdentityAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIAMIdentityAdminServiceUpdateUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUser(ctx, req.(*UpdateUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*User)
		return ctx.Result(200, reply)
	}
}

type IAMIdentityAdminServiceHTTPClient interface {
	AssignUserToGroup(ctx context.Context, req *AssignUserToGroupRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	CreateGroup(ctx context.Context, req *CreateGroupRequest, opts ...http.CallOption) (rsp *Group, err error)
	CreateUser(ctx context.Context, req *CreateUserRequest, opts ...http.CallOption) (rsp *User, err error)
	DeleteGroup(ctx context.Context, req *DeleteGroupRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteUser(ctx context.Context, req *DeleteUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DisableUser(ctx context.Context, req *DisableUserRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	RemoveUserFromGroup(ctx context.Context, req *RemoveUserFromGroupRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateGroup(ctx context.Context, req *UpdateGroupRequest, opts ...http.CallOption) (rsp *Group, err error)
	UpdateUser(ctx context.Context, req *UpdateUserRequest, opts ...http.CallOption) (rsp *User, err error)
}

type IAMIdentityAdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIAMIdentityAdminServiceHTTPClient(client *http.Client) IAMIdentityAdminServiceHTTPClient {
	return &IAMIdentityAdminServiceHTTPClientImpl{client}
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) AssignUserToGroup(ctx context.Context, in *AssignUserToGroupRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/iam/orgs/{org_id}/groups/{group_id}/users/{user_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceAssignUserToGroup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...http.CallOption) (*Group, error) {
	var out Group
	pattern := "/v1/iam/orgs/{org_id}/groups"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceCreateGroup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/iam/orgs/{org_id}/users"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceCreateUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/iam/orgs/{org_id}/groups/{group_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceDeleteGroup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/iam/orgs/{org_id}/users/{user_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceDeleteUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) DisableUser(ctx context.Context, in *DisableUserRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/iam/orgs/{org_id}/users/{user_id}:disable"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceDisableUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) RemoveUserFromGroup(ctx context.Context, in *RemoveUserFromGroupRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/iam/orgs/{org_id}/groups/{group_id}/users/{user_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceRemoveUserFromGroup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...http.CallOption) (*Group, error) {
	var out Group
	pattern := "/v1/iam/orgs/{org_id}/groups/{group_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceUpdateGroup),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IAMIdentityAdminServiceHTTPClientImpl) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...http.CallOption) (*User, error) {
	var out User
	pattern := "/v1/iam/orgs/{org_id}/users/{user_id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationIAMIdentityAdminServiceUpdateUser),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
